"""
seed_position_comps_batch2.py — Seed position comp records for RB, TE, OT, OG, C, IDL, ILB, OLB, S.

Usage:
    python scripts/seed_position_comps_batch2.py --apply 0   # dry run
    python scripts/seed_position_comps_batch2.py --apply 1   # write

Idempotent: INSERT OR IGNORE — re-running produces 0 inserts.
Backup before write. No schema changes needed (Migration 0046 already applied).
"""

import argparse
import shutil
import sqlite3
from datetime import datetime
from pathlib import Path

DB_PATH = Path(r"C:\DraftOS\data\edge\draftos.sqlite")
BACKUP_DIR = Path(r"C:\DraftOS\data\edge\backups")

# ---------------------------------------------------------------------------
# POSITION RECORDS — 79 rows across 9 positions
# is_fm_reference = 0 (position comps, not FM failure-mode references)
# pre_draft_signal = NULL (not set for position comps)
# ---------------------------------------------------------------------------

POSITION_RECORDS = [

    # -------------------------------------------------------------------------
    # RB — 16 records
    # -------------------------------------------------------------------------
    {
        "player_name": "Derrick Henry",
        "position": "RB",
        "archetype_code": "RB-1",
        "mechanism": "Carry accumulation workhorse; size-speed punisher who wins through physicality and volume",
        "translation_outcome": "HIT",
        "fm_code": None,
        "fm_mechanism": None,
        "outcome_summary": "Elite workhorse RB; 2000+ yards twice; carry volume validates archetype",
        "era_bracket": "2016-present",
        "peak_years": "2019-2021",
        "comp_confidence": "A",
        "scheme_context": "Tennessee Titans run-first; Vrabel system; extreme volume",
        "signature_trait": "Contact balance + acceleration through traffic",
        "is_fm_reference": 0,
    },
    {
        "player_name": "Frank Gore",
        "position": "RB",
        "archetype_code": "RB-1",
        "mechanism": "Elite durability workhorse; late-career efficiency; contact absorption at high volume",
        "translation_outcome": "HIT",
        "fm_code": None,
        "fm_mechanism": None,
        "outcome_summary": "All-time carry leader; 2000+ NFL carries; longevity proof of archetype ceiling",
        "era_bracket": "2005-2019",
        "peak_years": "2005-2012",
        "comp_confidence": "A",
        "scheme_context": "San Francisco zone-run; multiple OC systems; schematically versatile",
        "signature_trait": "Pad level + interior contact absorption",
        "is_fm_reference": 0,
    },
    {
        "player_name": "Trent Richardson",
        "position": "RB",
        "archetype_code": "RB-1",
        "mechanism": "Physical workhorse with volume role; contact balance rated elite; translational ceiling not met",
        "translation_outcome": "MISS",
        "fm_code": "FM-2",
        "fm_mechanism": "Contested-carry efficiency collapse; YPC below league average despite elite athleticism; scheme dependency masked college production",
        "outcome_summary": "3rd overall pick; never topped 4 YPC; illustrates carry-volume workhorse bust pattern",
        "era_bracket": "2012-2017",
        "peak_years": "None — never reached ceiling",
        "comp_confidence": "A",
        "scheme_context": "Alabama Power-I; Saban scheme inflated contact stats; NFL zone schemes exposed YPA limits",
        "signature_trait": "Physical measurables without translational efficiency",
        "is_fm_reference": 0,
    },
    {
        "player_name": "Marshawn Lynch",
        "position": "RB",
        "archetype_code": "RB-1",
        "mechanism": "Beast Mode contact absorber; elite yards-after-contact; physicality-driven workhorse",
        "translation_outcome": "HIT",
        "fm_code": None,
        "fm_mechanism": None,
        "outcome_summary": "Career renaissance in Seattle; 1200+ yards multiple seasons; contact-based workhorse prototype",
        "era_bracket": "2007-2018",
        "peak_years": "2011-2015",
        "comp_confidence": "A",
        "scheme_context": "Seattle power-run; Pete Carroll gap-scheme; volume role in run-first offense",
        "signature_trait": "Yards-after-contact; broken tackle rate",
        "is_fm_reference": 0,
    },
    {
        "player_name": "Christian McCaffrey",
        "position": "RB",
        "archetype_code": "RB-2",
        "mechanism": "Receiving back with elite open-field threat; dual-use weapon; receiving role primary",
        "translation_outcome": "HIT",
        "fm_code": None,
        "fm_mechanism": None,
        "outcome_summary": "Highest-paid RB; 1000-1000 candidate; dual-threat ceiling prototype",
        "era_bracket": "2017-present",
        "peak_years": "2019, 2023",
        "comp_confidence": "A",
        "scheme_context": "Carolina/San Francisco West Coast; pass-catcher role essential to value",
        "signature_trait": "Route running + burst + pass-pro awareness",
        "is_fm_reference": 0,
    },
    {
        "player_name": "Alvin Kamara",
        "position": "RB",
        "archetype_code": "RB-2",
        "mechanism": "Pass-first dual-threat; elite receiving efficiency; scheme-specific but versatile value",
        "translation_outcome": "HIT",
        "fm_code": None,
        "fm_mechanism": None,
        "outcome_summary": "Multiple Pro Bowls; top receiving RB of era; dual-use value realized",
        "era_bracket": "2017-present",
        "peak_years": "2017-2020",
        "comp_confidence": "A",
        "scheme_context": "New Orleans Sean Payton; pass-catcher role explicit; space creation system",
        "signature_trait": "Elusiveness in space + hands + receiving line",
        "is_fm_reference": 0,
    },
    {
        "player_name": "Darren Sproles",
        "position": "RB",
        "archetype_code": "RB-3",
        "mechanism": "Undersized speed back; return specialist + pass-catcher; receiving volume over carry role",
        "translation_outcome": "HIT",
        "fm_code": None,
        "fm_mechanism": None,
        "outcome_summary": "Elite special teams + receiving RB; 1000 scrimmage yards multiple seasons; archetype realized",
        "era_bracket": "2005-2019",
        "peak_years": "2011-2014",
        "comp_confidence": "A",
        "scheme_context": "San Diego/New Orleans/Philadelphia; pass-catcher and returner; size not limiting",
        "signature_trait": "Elusiveness in space; return ability; receiving precision",
        "is_fm_reference": 0,
    },
    {
        "player_name": "Shane Vereen",
        "position": "RB",
        "archetype_code": "RB-3",
        "mechanism": "Pass-first receiving back; route-runner; limited carry utility but elite in space",
        "translation_outcome": "HIT",
        "fm_code": None,
        "fm_mechanism": None,
        "outcome_summary": "New England third-down back prototype; receiving-role value fully realized",
        "era_bracket": "2011-2018",
        "peak_years": "2013-2015",
        "comp_confidence": "B",
        "scheme_context": "New England West Coast; Belichick system; pass-first role essential",
        "signature_trait": "Route precision + catch rate + YAC",
        "is_fm_reference": 0,
    },
    {
        "player_name": "Chris Johnson",
        "position": "RB",
        "archetype_code": "RB-4",
        "mechanism": "Speed burner; gap-cut north-south; 40-time translates to long-speed separation",
        "translation_outcome": "HIT",
        "fm_code": None,
        "fm_mechanism": None,
        "outcome_summary": "2000-yard season; fastest 40 time at Combine; speed-based archetype fully validated",
        "era_bracket": "2008-2016",
        "peak_years": "2009-2012",
        "comp_confidence": "A",
        "scheme_context": "Tennessee zone-run; Fisher system; gap-cut designed for speed exploitation",
        "signature_trait": "Long speed + burst + north-south gap decisiveness",
        "is_fm_reference": 0,
    },
    {
        "player_name": "Rashaad Penny",
        "position": "RB",
        "archetype_code": "RB-4",
        "mechanism": "Speed back; explosive burst; carry accumulation blocked by injury; potential unrealized",
        "translation_outcome": "MISS",
        "fm_code": "FM-4",
        "fm_mechanism": "Carry Accumulation Clock — speed back who never accumulated enough carries to establish NFL level; injury-shortened windows compressed ceiling",
        "outcome_summary": "27th overall pick; never established as starter; speed without durability = archetype ceiling missed",
        "era_bracket": "2018-2023",
        "peak_years": "2021 (partial)",
        "comp_confidence": "A",
        "scheme_context": "Seattle zone-run; Carroll system; speed role never consistently realized",
        "signature_trait": "Elite burst + acceleration; limited by availability",
        "is_fm_reference": 0,
    },
    {
        "player_name": "Jamaal Charles",
        "position": "RB",
        "archetype_code": "RB-4",
        "mechanism": "Elite efficiency speed back; YPC leader; open-field threat; dual-use with receiving",
        "translation_outcome": "HIT",
        "fm_code": None,
        "fm_mechanism": None,
        "outcome_summary": "Career 5.5 YPC — all-time record; speed-efficiency prototype; multiple Pro Bowls",
        "era_bracket": "2008-2016",
        "peak_years": "2010-2014",
        "comp_confidence": "A",
        "scheme_context": "Kansas City Reid West Coast; zone-run efficiency; dual-use role",
        "signature_trait": "Contact avoidance + burst + YPC efficiency",
        "is_fm_reference": 0,
    },
    {
        "player_name": "De'Von Achane",
        "position": "RB",
        "archetype_code": "RB-4",
        "mechanism": "Sprint-speed back; elite 40-time translates; explosive burst + receiving = modern speed prototype",
        "translation_outcome": "HIT",
        "fm_code": None,
        "fm_mechanism": None,
        "outcome_summary": "Fastest active RB; immediate impact in Miami; speed-to-NFL translation validated",
        "era_bracket": "2023-present",
        "peak_years": "2023",
        "comp_confidence": "B",
        "scheme_context": "Miami McDaniel system; space creation; speed exploitation scheme",
        "signature_trait": "Sprint speed + burst + receiving in space",
        "is_fm_reference": 0,
    },
    {
        "player_name": "LaDainian Tomlinson",
        "position": "RB",
        "archetype_code": "RB-5",
        "mechanism": "Complete back; vision + speed + power + receiving; all-surface weapon; prototypical ceiling",
        "translation_outcome": "HIT",
        "fm_code": None,
        "fm_mechanism": None,
        "outcome_summary": "MVP; all-time TD record (28 in 2006); Hall of Fame; complete archetype validation",
        "era_bracket": "2001-2011",
        "peak_years": "2003-2007",
        "comp_confidence": "A",
        "scheme_context": "San Diego West Coast; Norv Turner system; all-surface role",
        "signature_trait": "Vision + balance + receiving + red-zone efficiency",
        "is_fm_reference": 0,
    },
    {
        "player_name": "Saquon Barkley",
        "position": "RB",
        "archetype_code": "RB-5",
        "mechanism": "Elite athleticism all-surface weapon; contact power + receiving + speed; elite measurables",
        "translation_outcome": "HIT",
        "fm_code": None,
        "fm_mechanism": None,
        "outcome_summary": "2024 Eagles Super Bowl; 2000-yard season; complete back archetype realized",
        "era_bracket": "2018-present",
        "peak_years": "2018, 2024",
        "comp_confidence": "A",
        "scheme_context": "New York Giants + Philadelphia Eagles; multiple schemes; scheme-versatile complete back",
        "signature_trait": "Elite burst + power + pass-catching + contact balance",
        "is_fm_reference": 0,
    },
    {
        "player_name": "Todd Gurley",
        "position": "RB",
        "archetype_code": "RB-5",
        "mechanism": "Complete back; vision-power-speed; early peak; injury compressed ceiling",
        "translation_outcome": "HIT",
        "fm_code": None,
        "fm_mechanism": None,
        "outcome_summary": "2× All-Pro; Offensive Player of Year; complete archetype before knee condition",
        "era_bracket": "2015-2021",
        "peak_years": "2017-2018",
        "comp_confidence": "A",
        "scheme_context": "Los Angeles Rams McVay system; zone-run heavy; all-surface role",
        "signature_trait": "Vision + burst + power + receiving efficiency",
        "is_fm_reference": 0,
    },
    {
        "player_name": "Roger Craig",
        "position": "RB",
        "archetype_code": "RB-5",
        "mechanism": "First 1000-1000 back; complete archetype pioneer; vision + receiving + power",
        "translation_outcome": "HIT",
        "fm_code": None,
        "fm_mechanism": None,
        "outcome_summary": "Hall of Fame; prototype for dual-use complete backs; all-surface pioneer",
        "era_bracket": "1983-1993",
        "peak_years": "1985-1989",
        "comp_confidence": "A",
        "scheme_context": "San Francisco Walsh West Coast; Walsh/Montana system; pass-catcher role integral",
        "signature_trait": "Receiving precision + vision + contact balance",
        "is_fm_reference": 0,
    },

    # -------------------------------------------------------------------------
    # TE — 12 records
    # -------------------------------------------------------------------------
    {
        "player_name": "Travis Kelce",
        "position": "TE",
        "archetype_code": "TE-1",
        "mechanism": "Route-running receiving TE; YAC machine; contested-catch seam dominator",
        "translation_outcome": "HIT",
        "fm_code": None,
        "fm_mechanism": None,
        "outcome_summary": "Greatest receiving TE ever; multiple 1000-yard seasons; Hall of Fame lock",
        "era_bracket": "2013-present",
        "peak_years": "2016-2023",
        "comp_confidence": "A",
        "scheme_context": "Kansas City Reid West Coast; motion + crossing routes; primary receiving option",
        "signature_trait": "Route precision + YAC + separation at speed",
        "is_fm_reference": 0,
    },
    {
        "player_name": "Tony Gonzalez",
        "position": "TE",
        "archetype_code": "TE-1",
        "mechanism": "Route-running receiving TE pioneer; hands + separation + athleticism at position",
        "translation_outcome": "HIT",
        "fm_code": None,
        "fm_mechanism": None,
        "outcome_summary": "Hall of Fame; all-time receiving TE record at retirement; receiving archetype prototype",
        "era_bracket": "1997-2013",
        "peak_years": "2000-2008",
        "comp_confidence": "A",
        "scheme_context": "Kansas City + Atlanta; West Coast passing schemes; featured receiving role",
        "signature_trait": "Hands + route precision + contested-catch reliability",
        "is_fm_reference": 0,
    },
    {
        "player_name": "Greg Olsen",
        "position": "TE",
        "archetype_code": "TE-1",
        "mechanism": "Route-running seam TE; crossing pattern specialist; consistent mid-level receiving option",
        "translation_outcome": "HIT",
        "fm_code": None,
        "fm_mechanism": None,
        "outcome_summary": "Three 1000-yard seasons; Pro Bowl; seam receiver archetype validated",
        "era_bracket": "2007-2020",
        "peak_years": "2014-2016",
        "comp_confidence": "A",
        "scheme_context": "Carolina Ron Rivera; Cam Newton system; seam target in play-action",
        "signature_trait": "Route precision + seam separation + contested-catch",
        "is_fm_reference": 0,
    },
    {
        "player_name": "Hayden Hurst",
        "position": "TE",
        "archetype_code": "TE-1",
        "mechanism": "Route-running receiving TE; ceiling not reached; production role constrained",
        "translation_outcome": "MISS",
        "fm_code": "FM-3",
        "fm_mechanism": "Context Dependency — receiving TE whose production was scheme-gate controlled; never found consistent role to unlock ceiling",
        "outcome_summary": "25th overall pick; never topped 600 yards; receiving archetype bust by draft position",
        "era_bracket": "2018-2024",
        "peak_years": "2020 (partial)",
        "comp_confidence": "A",
        "scheme_context": "Baltimore/Atlanta/Cincinnati — multiple schemes; never featured receiving role secured",
        "signature_trait": "Athleticism without consistent route-to-target conversion",
        "is_fm_reference": 0,
    },
    {
        "player_name": "Rob Gronkowski",
        "position": "TE",
        "archetype_code": "TE-2",
        "mechanism": "Inline blocking + receiving hybrid; contested-catch red-zone weapon; dual-use prototype",
        "translation_outcome": "HIT",
        "fm_code": None,
        "fm_mechanism": None,
        "outcome_summary": "Greatest TE ever by many metrics; Hall of Fame; blocking + receiving dual ceiling",
        "era_bracket": "2010-2022",
        "peak_years": "2011-2018",
        "comp_confidence": "A",
        "scheme_context": "New England McDaniels; Brady system; run-block + seam-route dual role",
        "signature_trait": "Red-zone hands + run blocking + contested-catch dominance",
        "is_fm_reference": 0,
    },
    {
        "player_name": "Dallas Clark",
        "position": "TE",
        "archetype_code": "TE-2",
        "mechanism": "Receiving + blocking hybrid; Peyton Manning system TE; seam + run-block role",
        "translation_outcome": "HIT",
        "fm_code": None,
        "fm_mechanism": None,
        "outcome_summary": "Pro Bowl; 1000-yard season; dual-use hybrid TE archetype validated",
        "era_bracket": "2003-2012",
        "peak_years": "2007-2010",
        "comp_confidence": "A",
        "scheme_context": "Indianapolis Manning West Coast; Polian system; dual-use designed role",
        "signature_trait": "Route versatility + run block technique + hands",
        "is_fm_reference": 0,
    },
    {
        "player_name": "Kyle Pitts",
        "position": "TE",
        "archetype_code": "TE-2",
        "mechanism": "Freakish athleticism hybrid TE; WR-route TE ceiling; system dependency exposed",
        "translation_outcome": "MISS",
        "fm_code": "FM-3",
        "fm_mechanism": "Context Dependency — elite athleticism trapped in QB/scheme instability; Falcons' OC + QB carousel compressed ceiling",
        "outcome_summary": "4th overall pick; 1000 yards rookie only; production collapsed with scheme instability",
        "era_bracket": "2021-present",
        "peak_years": "2021",
        "comp_confidence": "A",
        "scheme_context": "Atlanta Falcons; multiple OC changes; never found consistent scheme home for athleticism",
        "signature_trait": "WR-route athleticism without scheme to deploy it",
        "is_fm_reference": 0,
    },
    {
        "player_name": "Irv Smith Jr.",
        "position": "TE",
        "archetype_code": "TE-2",
        "mechanism": "Hybrid receiving TE; athleticism + route versatility; ceiling blocked by role and injury",
        "translation_outcome": "MISS",
        "fm_code": "FM-4",
        "fm_mechanism": "Carry Accumulation Clock equivalent — never accumulated enough target volume to validate ceiling; injury + role competition blocked development window",
        "outcome_summary": "2nd round pick; never established; hybrid ceiling compressed by availability",
        "era_bracket": "2019-present",
        "peak_years": "None — never reached ceiling",
        "comp_confidence": "B",
        "scheme_context": "Minnesota/Cincinnati — role player behind Rudolph then Chase",
        "signature_trait": "Athleticism without sustained target volume",
        "is_fm_reference": 0,
    },
    {
        "player_name": "Mark Andrews",
        "position": "TE",
        "archetype_code": "TE-3",
        "mechanism": "Red-zone target TE; contested-catch specialist; jump-ball efficiency primary mechanism",
        "translation_outcome": "HIT",
        "fm_code": None,
        "fm_mechanism": None,
        "outcome_summary": "Multiple Pro Bowls; elite red-zone TE; Lamar Jackson primary target; contested-catch archetype realized",
        "era_bracket": "2018-present",
        "peak_years": "2021-2023",
        "comp_confidence": "A",
        "scheme_context": "Baltimore Harbaugh + Lamar Jackson; red-zone + contested-catch role",
        "signature_trait": "Contested-catch + red-zone efficiency + jump-ball hands",
        "is_fm_reference": 0,
    },
    {
        "player_name": "George Kittle",
        "position": "TE",
        "archetype_code": "TE-3",
        "mechanism": "YAC machine + blocking TE; run-after-catch primary weapon; elite run blocker",
        "translation_outcome": "HIT",
        "fm_code": None,
        "fm_mechanism": None,
        "outcome_summary": "Single-season YAC record; multiple Pro Bowls; blocking + YAC dual prototype",
        "era_bracket": "2017-present",
        "peak_years": "2018-2022",
        "comp_confidence": "A",
        "scheme_context": "San Francisco Shanahan; zone-run + YAC routes; blocking essential to role",
        "signature_trait": "YAC ability + run-blocking dominance + contested-catch",
        "is_fm_reference": 0,
    },
    {
        "player_name": "Eric Ebron",
        "position": "TE",
        "archetype_code": "TE-3",
        "mechanism": "Athletic receiving TE; red-zone + seam target; drops and inconsistency limited ceiling",
        "translation_outcome": "MISS",
        "fm_code": "FM-1",
        "fm_mechanism": "Athleticism Mirage — elite measurables and athleticism grade; drops rate and contested-catch inconsistency exposed hands as limiting factor",
        "outcome_summary": "10th overall pick; 13 drops in 2016; athletic ceiling without hands reliability",
        "era_bracket": "2014-2022",
        "peak_years": "2018 (Colts — TD volume; not efficiency)",
        "comp_confidence": "A",
        "scheme_context": "Detroit/Indianapolis/Pittsburgh — hands inconsistency consistent across all schemes",
        "signature_trait": "Athleticism without reliable hands",
        "is_fm_reference": 0,
    },
    {
        "player_name": "Zach Ertz",
        "position": "TE",
        "archetype_code": "TE-3",
        "mechanism": "Route-precision TE; intermediate chain-mover; sustained volume + efficiency across system",
        "translation_outcome": "HIT",
        "fm_code": None,
        "fm_mechanism": None,
        "outcome_summary": "Super Bowl catch; multiple 800-yard seasons; sustained chain-mover production",
        "era_bracket": "2013-present",
        "peak_years": "2017-2019",
        "comp_confidence": "A",
        "scheme_context": "Philadelphia Pederson West Coast; intermediate route specialist; Carson Wentz primary target",
        "signature_trait": "Route precision + intermediate YAC + volume reliability",
        "is_fm_reference": 0,
    },

    # -------------------------------------------------------------------------
    # OT — 10 records
    # -------------------------------------------------------------------------
    {
        "player_name": "Jonathan Ogden",
        "position": "OT",
        "archetype_code": "OT-1",
        "mechanism": "Anchor-dominant left tackle; elite pass-set technique + run-block power; physical dominance",
        "translation_outcome": "HIT",
        "fm_code": None,
        "fm_mechanism": None,
        "outcome_summary": "Hall of Fame; 11 Pro Bowls; left tackle prototype for size-power archetype",
        "era_bracket": "1996-2007",
        "peak_years": "1999-2005",
        "comp_confidence": "A",
        "scheme_context": "Baltimore power-run; Billick system; left tackle as franchise anchor",
        "signature_trait": "Length + anchor strength + pass-set technique",
        "is_fm_reference": 0,
    },
    {
        "player_name": "Trent Williams",
        "position": "OT",
        "archetype_code": "OT-1",
        "mechanism": "Athletic anchor LT; power + athleticism dual mechanism; elite run-block + pass-set",
        "translation_outcome": "HIT",
        "fm_code": None,
        "fm_mechanism": None,
        "outcome_summary": "Considered best OT of generation; multiple All-Pro; athletic-power OT ceiling",
        "era_bracket": "2010-present",
        "peak_years": "2018-2024",
        "comp_confidence": "A",
        "scheme_context": "Washington/San Francisco; zone-run + power; scheme-versatile anchor",
        "signature_trait": "Athleticism + anchor + run-block aggression",
        "is_fm_reference": 0,
    },
    {
        "player_name": "Jake Long",
        "position": "OT",
        "archetype_code": "OT-1",
        "mechanism": "Size-power LT; elite pass-set + anchor; injury-shortened career compressed ceiling",
        "translation_outcome": "MISS",
        "fm_code": "FM-4",
        "fm_mechanism": "Carry Accumulation Clock equivalent — OT who never accumulated enough reps to establish durability; knee/shoulder cascade compressed effectiveness window",
        "outcome_summary": "1st overall pick; 4 Pro Bowls early; then injury spiral; never reached sustained ceiling",
        "era_bracket": "2008-2016",
        "peak_years": "2008-2011",
        "comp_confidence": "A",
        "scheme_context": "Miami + multiple teams; health cascade = role and team loss across career",
        "signature_trait": "Elite measurables + power without durability",
        "is_fm_reference": 0,
    },
    {
        "player_name": "Orlando Pace",
        "position": "OT",
        "archetype_code": "OT-1",
        "mechanism": "Power-first anchor LT; run-block mauler + pass-set technique pioneer; Hall of Fame ceiling",
        "translation_outcome": "HIT",
        "fm_code": None,
        "fm_mechanism": None,
        "outcome_summary": "Hall of Fame; Greatest Show on Turf anchor; power-run OT prototype",
        "era_bracket": "1997-2009",
        "peak_years": "1999-2005",
        "comp_confidence": "A",
        "scheme_context": "St. Louis Rams Mike Martz; Greatest Show on Turf; left tackle as anchor",
        "signature_trait": "Power anchor + technique precision + run-block dominance",
        "is_fm_reference": 0,
    },
    {
        "player_name": "Joe Thomas",
        "position": "OT",
        "archetype_code": "OT-2",
        "mechanism": "Technique-dominant LT; elite footwork + pass-set; pure technique archetype without power reliance",
        "translation_outcome": "HIT",
        "fm_code": None,
        "fm_mechanism": None,
        "outcome_summary": "10× Pro Bowl; 10,363 consecutive snaps; technique-first OT ceiling validated",
        "era_bracket": "2007-2018",
        "peak_years": "2007-2016",
        "comp_confidence": "A",
        "scheme_context": "Cleveland; multiple systems; technique translated despite poor team context",
        "signature_trait": "Footwork precision + pass-set + hand placement technique",
        "is_fm_reference": 0,
    },
    {
        "player_name": "D'Brickashaw Ferguson",
        "position": "OT",
        "archetype_code": "OT-2",
        "mechanism": "Technique-first LT; athleticism + footwork; durability + consistent technique across career",
        "translation_outcome": "HIT",
        "fm_code": None,
        "fm_mechanism": None,
        "outcome_summary": "Never missed a snap in 10 seasons; technique-durability OT prototype",
        "era_bracket": "2006-2015",
        "peak_years": "2009-2014",
        "comp_confidence": "A",
        "scheme_context": "New York Jets; multiple HC/OC systems; scheme-versatile technique OT",
        "signature_trait": "Footwork + lateral quickness + technique consistency",
        "is_fm_reference": 0,
    },
    {
        "player_name": "Andrew Whitworth",
        "position": "OT",
        "archetype_code": "OT-2",
        "mechanism": "Veteran technique OT; late-peak; footwork + awareness; Super Bowl LVI anchor at age 40",
        "translation_outcome": "HIT",
        "fm_code": None,
        "fm_mechanism": None,
        "outcome_summary": "Walter Payton Man of Year; Super Bowl LVI at 40; longevity + technique proof",
        "era_bracket": "2006-2021",
        "peak_years": "2016-2021",
        "comp_confidence": "A",
        "scheme_context": "Cincinnati/Los Angeles Rams; McVay zone-run; technique essential to late-career value",
        "signature_trait": "Technique precision + football IQ + awareness",
        "is_fm_reference": 0,
    },
    {
        "player_name": "Cordy Glenn",
        "position": "OT",
        "archetype_code": "OT-2",
        "mechanism": "Technique-primary LT; athleticism + footwork; health cascade limited ceiling",
        "translation_outcome": "MISS",
        "fm_code": "FM-4",
        "fm_mechanism": "Carry Accumulation Clock — technique OT who couldn't accumulate reps; injury cascade shortened effective windows across career",
        "outcome_summary": "High draft pick; multiple missed seasons; technique without durability = ceiling missed",
        "era_bracket": "2012-2020",
        "peak_years": "2012-2015 (partial)",
        "comp_confidence": "B",
        "scheme_context": "Buffalo/Cincinnati; multiple systems; health the constant constraint",
        "signature_trait": "Athleticism + technique without availability",
        "is_fm_reference": 0,
    },
    {
        "player_name": "Joe Staley",
        "position": "OT",
        "archetype_code": "OT-3",
        "mechanism": "Zone-run specialist OT; athletic + finesse; scheme-specific but sustained elite production",
        "translation_outcome": "HIT",
        "fm_code": None,
        "fm_mechanism": None,
        "outcome_summary": "6 Pro Bowls; Shanahan zone-run anchor; zone-block specialist prototype",
        "era_bracket": "2007-2020",
        "peak_years": "2011-2019",
        "comp_confidence": "A",
        "scheme_context": "San Francisco Harbaugh/Shanahan; zone-run heavy; athletic finesse OT role",
        "signature_trait": "Athletic footwork + zone-cut angles + finesse technique",
        "is_fm_reference": 0,
    },
    {
        "player_name": "Greg Robinson",
        "position": "OT",
        "archetype_code": "OT-3",
        "mechanism": "Athletic zone-specialist OT; elite athleticism without technique development; bust case",
        "translation_outcome": "MISS",
        "fm_code": "FM-2",
        "fm_mechanism": "Contested-Assignment Efficiency — elite RAS + athleticism without technique to win assignments; scheme exposure revealed hand-punch deficiencies",
        "outcome_summary": "2nd overall pick; released multiple times; pure athleticism without technique = bust",
        "era_bracket": "2014-2022",
        "peak_years": "None — never reached ceiling",
        "comp_confidence": "A",
        "scheme_context": "St. Louis/Detroit/Cleveland/Minnesota — athleticism exposed across all schemes",
        "signature_trait": "Elite athleticism without translational technique",
        "is_fm_reference": 0,
    },

    # -------------------------------------------------------------------------
    # OG — 6 records
    # -------------------------------------------------------------------------
    {
        "player_name": "Quenton Nelson",
        "position": "OG",
        "archetype_code": "OG-1",
        "mechanism": "Dominant run-blocking guard; power + technique; immediate impact; franchise-level guard ceiling",
        "translation_outcome": "HIT",
        "fm_code": None,
        "fm_mechanism": None,
        "outcome_summary": "Immediate All-Pro; considered best guard of generation; run-block prototype",
        "era_bracket": "2018-present",
        "peak_years": "2018-2023",
        "comp_confidence": "A",
        "scheme_context": "Indianapolis Frank Reich/Shane Steichen; gap-run heavy; run-block guard as anchor",
        "signature_trait": "Power run-block + pass-set anchor + technique precision",
        "is_fm_reference": 0,
    },
    {
        "player_name": "Zack Martin",
        "position": "OG",
        "archetype_code": "OG-1",
        "mechanism": "Technique-first guard; elite pass-set + run-block; sustained elite production",
        "translation_outcome": "HIT",
        "fm_code": None,
        "fm_mechanism": None,
        "outcome_summary": "7 All-Pro selections; Hall of Fame trajectory; technique-dominant guard ceiling",
        "era_bracket": "2014-present",
        "peak_years": "2015-2023",
        "comp_confidence": "A",
        "scheme_context": "Dallas Cowboys; zone + gap run; technique OG in multi-scheme system",
        "signature_trait": "Hand placement + footwork + combo-block technique",
        "is_fm_reference": 0,
    },
    {
        "player_name": "Chance Warmack",
        "position": "OG",
        "archetype_code": "OG-1",
        "mechanism": "Power-run guard; elite combine measurables; scheme dependency exposed; bust",
        "translation_outcome": "MISS",
        "fm_code": "FM-3",
        "fm_mechanism": "Context Dependency — power guard whose ceiling required specific gap-run scheme; Tennessee coaching instability + system changes exposed technical gaps",
        "outcome_summary": "10th overall pick; never started after year 3; power without scheme fit = bust",
        "era_bracket": "2013-2017",
        "peak_years": "None — never reached ceiling",
        "comp_confidence": "A",
        "scheme_context": "Tennessee; HC/OC instability; Alabama power scheme not replicated in NFL",
        "signature_trait": "Power measurables without adaptable technique",
        "is_fm_reference": 0,
    },
    {
        "player_name": "Logan Mankins",
        "position": "OG",
        "archetype_code": "OG-2",
        "mechanism": "Nasty run-blocking guard; physical-first; sustained elite career across scheme types",
        "translation_outcome": "HIT",
        "fm_code": None,
        "fm_mechanism": None,
        "outcome_summary": "7 Pro Bowls; Hall of Fame finalist; physical-first guard prototype",
        "era_bracket": "2005-2015",
        "peak_years": "2007-2013",
        "comp_confidence": "A",
        "scheme_context": "New England Belichick; zone + power hybrid; technique + physicality dual role",
        "signature_trait": "Physical aggression + hand fighting + run-block dominance",
        "is_fm_reference": 0,
    },
    {
        "player_name": "Larry Allen",
        "position": "OG",
        "archetype_code": "OG-2",
        "mechanism": "Power-dominant all-surface guard; historical strength + technique; prototype for position",
        "translation_outcome": "HIT",
        "fm_code": None,
        "fm_mechanism": None,
        "outcome_summary": "Hall of Fame; 7 All-Pro; considered greatest guard in NFL history; power prototype",
        "era_bracket": "1994-2007",
        "peak_years": "1995-2003",
        "comp_confidence": "A",
        "scheme_context": "Dallas Cowboys; Switzer/Parcells power-run; dominant guard role",
        "signature_trait": "Elite power + technique + all-surface versatility",
        "is_fm_reference": 0,
    },
    {
        "player_name": "Teven Jenkins",
        "position": "OG",
        "archetype_code": "OG-2",
        "mechanism": "Physical-aggression guard; nasty run-blocker; back surgery + role instability limited ceiling",
        "translation_outcome": "MISS",
        "fm_code": "FM-4",
        "fm_mechanism": "Carry Accumulation Clock — guard who couldn't accumulate snaps; back surgery at draft + role competition = availability crater",
        "outcome_summary": "35th pick; back surgery pre-draft; role player at best; physical ceiling never established",
        "era_bracket": "2021-present",
        "peak_years": "None — never established",
        "comp_confidence": "B",
        "scheme_context": "Chicago/Las Vegas; multiple schemes; health the primary constraint",
        "signature_trait": "Physical aggression without snap availability",
        "is_fm_reference": 0,
    },

    # -------------------------------------------------------------------------
    # C — 8 records
    # -------------------------------------------------------------------------
    {
        "player_name": "Jeff Saturday",
        "position": "C",
        "archetype_code": "C-1",
        "mechanism": "Communication-anchor center; line call leadership + technique; Peyton Manning system orchestrator",
        "translation_outcome": "HIT",
        "fm_code": None,
        "fm_mechanism": None,
        "outcome_summary": "5 Pro Bowls; Peyton Manning's primary protection anchor; communication-first center prototype",
        "era_bracket": "1999-2012",
        "peak_years": "2003-2010",
        "comp_confidence": "A",
        "scheme_context": "Indianapolis Manning West Coast; Polian system; communication anchor role",
        "signature_trait": "Line-call leadership + hand technique + anchor",
        "is_fm_reference": 0,
    },
    {
        "player_name": "Mike Pouncey",
        "position": "C",
        "archetype_code": "C-1",
        "mechanism": "Athletic anchor center; zone-run pull + communication; injury compressed ceiling",
        "translation_outcome": "HIT",
        "fm_code": None,
        "fm_mechanism": None,
        "outcome_summary": "Multiple Pro Bowls; athletic center prototype; career shortened by hip injury",
        "era_bracket": "2011-2020",
        "peak_years": "2012-2018",
        "comp_confidence": "A",
        "scheme_context": "Miami/Los Angeles Chargers; zone-run + pass-protection anchor",
        "signature_trait": "Athleticism + zone-pull + communication leadership",
        "is_fm_reference": 0,
    },
    {
        "player_name": "Travis Frederick",
        "position": "C",
        "archetype_code": "C-1",
        "mechanism": "Technique-dominant anchor center; line-call precision + power; illness-shortened peak",
        "translation_outcome": "HIT",
        "fm_code": None,
        "fm_mechanism": None,
        "outcome_summary": "5 Pro Bowls; Guillain-Barré shortened career; elite technique during active years",
        "era_bracket": "2013-2019",
        "peak_years": "2014-2019",
        "comp_confidence": "A",
        "scheme_context": "Dallas Cowboys Scott Linehan; zone + gap hybrid; communication anchor",
        "signature_trait": "Technique precision + line-call leadership + anchor strength",
        "is_fm_reference": 0,
    },
    {
        "player_name": "Maurkice Pouncey",
        "position": "C",
        "archetype_code": "C-1",
        "mechanism": "Power-athletic anchor center; run-block + pass-set; Steelers physical play anchor",
        "translation_outcome": "HIT",
        "fm_code": None,
        "fm_mechanism": None,
        "outcome_summary": "9 Pro Bowls; anchor of Pittsburgh OL for decade; power-run center prototype",
        "era_bracket": "2010-2020",
        "peak_years": "2012-2019",
        "comp_confidence": "A",
        "scheme_context": "Pittsburgh Steelers; gap-run + power; physical anchor center role",
        "signature_trait": "Power anchor + run-block dominance + communication",
        "is_fm_reference": 0,
    },
    {
        "player_name": "Ryan Jensen",
        "position": "C",
        "archetype_code": "C-2",
        "mechanism": "Physical-aggression center; nasty run-blocker; late-round value; injury interrupted peak",
        "translation_outcome": "HIT",
        "fm_code": None,
        "fm_mechanism": None,
        "outcome_summary": "Super Bowl LV anchor; free-agent contract validated; physical-first center ceiling",
        "era_bracket": "2013-present",
        "peak_years": "2018-2022",
        "comp_confidence": "B",
        "scheme_context": "Tampa Bay Brady era; Arians system; run-block physical center role",
        "signature_trait": "Nastiness + run-block aggression + anchor power",
        "is_fm_reference": 0,
    },
    {
        "player_name": "Frank Ragnow",
        "position": "C",
        "archetype_code": "C-2",
        "mechanism": "Athletic technique center; zone-run + pass-set; elite when healthy; injury limited availability",
        "translation_outcome": "HIT",
        "fm_code": None,
        "fm_mechanism": None,
        "outcome_summary": "Pro Bowl; considered top center in game; athletic technique ceiling when available",
        "era_bracket": "2018-present",
        "peak_years": "2019-2023",
        "comp_confidence": "A",
        "scheme_context": "Detroit Lions; Campbell/Bevell run-first; athletic center in zone-gap hybrid",
        "signature_trait": "Athleticism + zone-pull + technique + communication",
        "is_fm_reference": 0,
    },
    {
        "player_name": "David Andrews",
        "position": "C",
        "archetype_code": "C-3",
        "mechanism": "Cerebral communication-first center; system quarterback of OL; Belichick schematic fit",
        "translation_outcome": "HIT",
        "fm_code": None,
        "fm_mechanism": None,
        "outcome_summary": "UDFA to starting center; multiple Super Bowl anchor; communication-first value",
        "era_bracket": "2015-present",
        "peak_years": "2016-2022",
        "comp_confidence": "A",
        "scheme_context": "New England Belichick; system anchor; brain-trust center role essential",
        "signature_trait": "Line-call IQ + communication + scheme-fit reliability",
        "is_fm_reference": 0,
    },
    {
        "player_name": "Cody Whitehair",
        "position": "C",
        "archetype_code": "C-3",
        "mechanism": "Communication-technique center; consistent production; never elite; reliable starter archetype",
        "translation_outcome": "HIT",
        "fm_code": None,
        "fm_mechanism": None,
        "outcome_summary": "Long-time starter; reliable production without Pro Bowl ceiling; communication-value center",
        "era_bracket": "2016-present",
        "peak_years": "2018-2022",
        "comp_confidence": "B",
        "scheme_context": "Chicago Bears; multiple OC systems; consistent starter value in varied schemes",
        "signature_trait": "Technique consistency + communication + reliability",
        "is_fm_reference": 0,
    },

    # -------------------------------------------------------------------------
    # IDL — 7 records
    # -------------------------------------------------------------------------
    {
        "player_name": "Geno Atkins",
        "position": "IDL",
        "archetype_code": "IDL-1",
        "mechanism": "Interior penetrator; elite quickness + hand technique; A-gap pressure generator",
        "translation_outcome": "HIT",
        "fm_code": None,
        "fm_mechanism": None,
        "outcome_summary": "8 Pro Bowls; elite pass-rush IDL; penetration archetype at interior prototype",
        "era_bracket": "2010-2020",
        "peak_years": "2012-2018",
        "comp_confidence": "A",
        "scheme_context": "Cincinnati Bengals; 4-3 base; A-gap penetrator primary role",
        "signature_trait": "First-step quickness + hand speed + interior pressure",
        "is_fm_reference": 0,
    },
    {
        "player_name": "Aaron Donald",
        "position": "IDL",
        "archetype_code": "IDL-1",
        "mechanism": "Generational penetrator; unblockable first step + hand technique; interior disruption prototype",
        "translation_outcome": "HIT",
        "fm_code": None,
        "fm_mechanism": None,
        "outcome_summary": "Greatest IDL ever; 3× DPOY; Hall of Fame; interior penetration ceiling defined",
        "era_bracket": "2014-2022",
        "peak_years": "2017-2021",
        "comp_confidence": "A",
        "scheme_context": "Los Angeles Rams Wade Phillips; 3-4 + 4-3 hybrid; interior pass-rush central",
        "signature_trait": "Elite first step + hand technique + motor + counter package",
        "is_fm_reference": 0,
    },
    {
        "player_name": "Gerald McCoy",
        "position": "IDL",
        "archetype_code": "IDL-1",
        "mechanism": "Interior penetrator; athleticism-first + quickness; production despite poor team context",
        "translation_outcome": "HIT",
        "fm_code": None,
        "fm_mechanism": None,
        "outcome_summary": "6 Pro Bowls; elite production despite Tampa losing era; penetration value despite context",
        "era_bracket": "2010-2021",
        "peak_years": "2012-2017",
        "comp_confidence": "A",
        "scheme_context": "Tampa Bay; losing-era OL support; pressure generation despite scheme limitations",
        "signature_trait": "Athleticism + quickness + interior counter moves",
        "is_fm_reference": 0,
    },
    {
        "player_name": "Chris Jones",
        "position": "IDL",
        "archetype_code": "IDL-2",
        "mechanism": "Anchor + pass-rush hybrid IDL; length + power + interior quickness dual mechanism",
        "translation_outcome": "HIT",
        "fm_code": None,
        "fm_mechanism": None,
        "outcome_summary": "Multiple All-Pro; highest-paid IDL; anchor + penetration dual-ceiling prototype",
        "era_bracket": "2016-present",
        "peak_years": "2019-2024",
        "comp_confidence": "A",
        "scheme_context": "Kansas City Spagnuolo; 4-3 + 3-4 hybrid; interior anchor + pass-rush dual role",
        "signature_trait": "Length + power + first step + counter package",
        "is_fm_reference": 0,
    },
    {
        "player_name": "Haloti Ngata",
        "position": "IDL",
        "archetype_code": "IDL-2",
        "mechanism": "Anchor-dominant IDL; size + power + athleticism; run-stop anchor + occasional pass-rush",
        "translation_outcome": "HIT",
        "fm_code": None,
        "fm_mechanism": None,
        "outcome_summary": "5 Pro Bowls; Ravens anchor; size-power IDL prototype for run-defense",
        "era_bracket": "2006-2016",
        "peak_years": "2009-2014",
        "comp_confidence": "A",
        "scheme_context": "Baltimore Ravens Rex Ryan; 3-4 + 4-3 hybrid; nose tackle anchor role",
        "signature_trait": "Size + power + explosion + run-stop leverage",
        "is_fm_reference": 0,
    },
    {
        "player_name": "Solomon Thomas",
        "position": "IDL",
        "archetype_code": "IDL-1",
        "mechanism": "Penetrator IDL; athleticism-based; role fluidity limited production; bust case",
        "translation_outcome": "MISS",
        "fm_code": "FM-3",
        "fm_mechanism": "Context Dependency — penetrator role not clearly defined in San Francisco system; position group competition and role ambiguity suppressed production",
        "outcome_summary": "3rd overall pick; never reached 5 sacks in a season; role ambiguity = ceiling suppressed",
        "era_bracket": "2017-present",
        "peak_years": "None — never established",
        "comp_confidence": "A",
        "scheme_context": "San Francisco/Las Vegas/New York Jets — role instability consistent across organizations",
        "signature_trait": "Athleticism without defined role exploitation",
        "is_fm_reference": 0,
    },
    {
        "player_name": "Vita Vea",
        "position": "IDL",
        "archetype_code": "IDL-2",
        "mechanism": "Anchor-dominant nose tackle; elite run-stop leverage; gap-eating presence; occasional pass-rush value",
        "translation_outcome": "HIT",
        "fm_code": None,
        "fm_mechanism": None,
        "outcome_summary": "Pro Bowl; Tampa Super Bowl anchor; nose tackle anchor prototype in modern era",
        "era_bracket": "2018-present",
        "peak_years": "2020-2023",
        "comp_confidence": "A",
        "scheme_context": "Tampa Bay Todd Bowles 3-4; nose tackle anchor; gap-eat + occasional rush",
        "signature_trait": "Leverage + gap-eat + anchor + surprise pass-rush",
        "is_fm_reference": 0,
    },

    # -------------------------------------------------------------------------
    # ILB — 6 records
    # -------------------------------------------------------------------------
    {
        "player_name": "Ray Lewis",
        "position": "ILB",
        "archetype_code": "ILB-1",
        "mechanism": "All-surface impact linebacker; sideline-to-sideline range + run-stop dominance + pass coverage",
        "translation_outcome": "HIT",
        "fm_code": None,
        "fm_mechanism": None,
        "outcome_summary": "Hall of Fame; 2× Super Bowl; considered greatest LB of all time; complete archetype",
        "era_bracket": "1996-2012",
        "peak_years": "1999-2009",
        "comp_confidence": "A",
        "scheme_context": "Baltimore Ravens Rex Ryan; 4-3 base; Mike linebacker as defensive anchor",
        "signature_trait": "Football IQ + range + run-stop leverage + coverage awareness",
        "is_fm_reference": 0,
    },
    {
        "player_name": "Bobby Wagner",
        "position": "ILB",
        "archetype_code": "ILB-1",
        "mechanism": "Sideline-to-sideline impact ILB; run-stop + coverage + blitz; complete modern prototype",
        "translation_outcome": "HIT",
        "fm_code": None,
        "fm_mechanism": None,
        "outcome_summary": "8 All-Pro; two Super Bowls; highest-paid LB in history at peak; modern ILB ceiling",
        "era_bracket": "2012-present",
        "peak_years": "2015-2022",
        "comp_confidence": "A",
        "scheme_context": "Seattle Carroll Cover-3; mike linebacker anchor; run-stop + zone coverage dual role",
        "signature_trait": "Range + instincts + run-stop power + coverage reliability",
        "is_fm_reference": 0,
    },
    {
        "player_name": "Patrick Willis",
        "position": "ILB",
        "archetype_code": "ILB-1",
        "mechanism": "Elite athleticism ILB; run-stop + coverage; transcendent physical tools at position",
        "translation_outcome": "HIT",
        "fm_code": None,
        "fm_mechanism": None,
        "outcome_summary": "Hall of Fame; Rookie of Year + multiple All-Pro; athleticism-first ILB prototype",
        "era_bracket": "2007-2014",
        "peak_years": "2007-2013",
        "comp_confidence": "A",
        "scheme_context": "San Francisco Harbaugh; 4-3 base; physical-first linebacker role",
        "signature_trait": "Elite athleticism + speed + run-stop technique",
        "is_fm_reference": 0,
    },
    {
        "player_name": "Manti Te'o",
        "position": "ILB",
        "archetype_code": "ILB-1",
        "mechanism": "Sideline-to-sideline ILB prospect; college dominance without athletic ceiling; bust case",
        "translation_outcome": "MISS",
        "fm_code": "FM-1",
        "fm_mechanism": "Athleticism Mirage — production was product of Notre Dame scheme rather than translatable athleticism; NFL zone/man exposures revealed footspeed and range limitations",
        "outcome_summary": "2nd round pick; never started more than 7 games; college context inflated ILB grade",
        "era_bracket": "2013-2020",
        "peak_years": "None — never established",
        "comp_confidence": "A",
        "scheme_context": "San Diego/New Orleans; scheme exposure consistent; limitations universal",
        "signature_trait": "College dominance without translatable athleticism",
        "is_fm_reference": 0,
    },
    {
        "player_name": "Zach Thomas",
        "position": "ILB",
        "archetype_code": "ILB-2",
        "mechanism": "Instinct-first ILB; football IQ as primary mechanism; size-speed athleticism below elite",
        "translation_outcome": "HIT",
        "fm_code": None,
        "fm_mechanism": None,
        "outcome_summary": "Hall of Fame; 7 Pro Bowls; IQ-first prototype for undersized ILB ceiling",
        "era_bracket": "1996-2008",
        "peak_years": "1999-2006",
        "comp_confidence": "A",
        "scheme_context": "Miami Jimmy Johnson/Dave Wannstedt; 4-3 mike; instinct-based coverage + run-stop",
        "signature_trait": "Pre-snap read + pursuit angles + instinct-based production",
        "is_fm_reference": 0,
    },
    {
        "player_name": "Rolando McClain",
        "position": "ILB",
        "archetype_code": "ILB-2",
        "mechanism": "Physical-first ILB; elite run-stop potential; character and motivation collapse = bust",
        "translation_outcome": "MISS",
        "fm_code": "FM-6",
        "fm_mechanism": "Motor/Motivation gap — elite physical tools with documented motivation issues; multiple retirements + violations; professional commitment ceiling",
        "outcome_summary": "8th overall pick; retired at 24; returned; never consistent; motivation-bust prototype",
        "era_bracket": "2010-2016",
        "peak_years": "2011 (partial)",
        "comp_confidence": "A",
        "scheme_context": "Oakland/Dallas; multiple HC attempts; motivation floor consistent across contexts",
        "signature_trait": "Physical tools without professional commitment",
        "is_fm_reference": 0,
    },

    # -------------------------------------------------------------------------
    # OLB — 7 records
    # -------------------------------------------------------------------------
    {
        "player_name": "Myles Garrett",
        "position": "OLB",
        "archetype_code": "OLB-1",
        "mechanism": "Elite pass-rush OLB; power + athleticism + hand technique; generational edge archetype",
        "translation_outcome": "HIT",
        "fm_code": None,
        "fm_mechanism": None,
        "outcome_summary": "DPOY; multiple All-Pro; franchise pass-rusher; power-athleticism OLB ceiling",
        "era_bracket": "2017-present",
        "peak_years": "2019-2024",
        "comp_confidence": "A",
        "scheme_context": "Cleveland Browns; 4-3 + 3-4 hybrid; edge-rush primary mechanism",
        "signature_trait": "Power + athleticism + hand technique + bull rush",
        "is_fm_reference": 0,
    },
    {
        "player_name": "Khalil Mack",
        "position": "OLB",
        "archetype_code": "OLB-1",
        "mechanism": "Complete edge defender; pass-rush + run-stop + coverage; DPOY-level ceiling",
        "translation_outcome": "HIT",
        "fm_code": None,
        "fm_mechanism": None,
        "outcome_summary": "DPOY 2016; $141M extension; complete OLB prototype across all defensive dimensions",
        "era_bracket": "2014-present",
        "peak_years": "2015-2022",
        "comp_confidence": "A",
        "scheme_context": "Oakland/Chicago/Los Angeles Chargers; 3-4 + 4-3; all-surface edge value",
        "signature_trait": "Pass-rush burst + bull rush + strip-sack hands + coverage awareness",
        "is_fm_reference": 0,
    },
    {
        "player_name": "Dee Ford",
        "position": "OLB",
        "archetype_code": "OLB-2",
        "mechanism": "Speed-rush OLB; elite get-off + bend; health cascade limited ceiling realization",
        "translation_outcome": "MISS",
        "fm_code": "FM-4",
        "fm_mechanism": "Carry Accumulation Clock — speed-rusher who couldn't accumulate snaps; back injury + roster instability = ceiling never established",
        "outcome_summary": "$87M extension; played 5 games total after; speed-rush ceiling without availability",
        "era_bracket": "2014-2021",
        "peak_years": "2018",
        "comp_confidence": "A",
        "scheme_context": "Kansas City/San Francisco — health cascade consistent; scheme not limiting factor",
        "signature_trait": "Elite speed-rush get-off without availability",
        "is_fm_reference": 0,
    },
    {
        "player_name": "Trey Hendrickson",
        "position": "OLB",
        "archetype_code": "OLB-2",
        "mechanism": "Speed-rush OLB; late bloomer; elite counter + speed combination; sustained production",
        "translation_outcome": "HIT",
        "fm_code": None,
        "fm_mechanism": None,
        "outcome_summary": "14.5 sacks in first Cincinnati season; consistent double-digit sack production; late-bloom prototype",
        "era_bracket": "2017-present",
        "peak_years": "2021-present",
        "comp_confidence": "A",
        "scheme_context": "Cincinnati Bengals; hybrid 4-3; speed-rush specialist in sub-package role",
        "signature_trait": "Speed-rush get-off + counter moves + late-bloom development arc",
        "is_fm_reference": 0,
    },
    {
        "player_name": "T.J. Watt",
        "position": "OLB",
        "archetype_code": "OLB-1",
        "mechanism": "Complete edge defender; DPOY-level production; pass-rush + run-stop + strip-sack elite",
        "translation_outcome": "HIT",
        "fm_code": None,
        "fm_mechanism": None,
        "outcome_summary": "DPOY 2021; Sack record (22.5 in 2021); complete OLB prototype of modern era",
        "era_bracket": "2017-present",
        "peak_years": "2019-present",
        "comp_confidence": "A",
        "scheme_context": "Pittsburgh Steelers; 3-4 OLB; all-surface edge defender role",
        "signature_trait": "Pass-rush technique + strip-sack hands + motor + run-stop leverage",
        "is_fm_reference": 0,
    },
    {
        "player_name": "Aldon Smith",
        "position": "OLB",
        "archetype_code": "OLB-2",
        "mechanism": "Speed-rush OLB; elite ceiling; off-field conduct collapses career = bust by availability",
        "translation_outcome": "MISS",
        "fm_code": "FM-6",
        "fm_mechanism": "Motor/Motivation gap — elite pass-rush athleticism; multiple suspensions + arrests + substance issues = professional commitment floor",
        "outcome_summary": "33.5 sacks in first 3 seasons; banned from NFL; professional-commitment bust prototype",
        "era_bracket": "2011-2021",
        "peak_years": "2011-2012",
        "comp_confidence": "A",
        "scheme_context": "San Francisco Harbaugh; elite production before conduct collapse",
        "signature_trait": "Elite speed-rush ceiling without professional reliability",
        "is_fm_reference": 0,
    },
    {
        "player_name": "Dwight Freeney",
        "position": "OLB",
        "archetype_code": "OLB-3",
        "mechanism": "Spin-move specialist; elite technique-based speed rusher; consistent production across career",
        "translation_outcome": "HIT",
        "fm_code": None,
        "fm_mechanism": None,
        "outcome_summary": "Hall of Fame; 125.5 career sacks; spin-move specialist prototype at OLB",
        "era_bracket": "2002-2017",
        "peak_years": "2004-2012",
        "comp_confidence": "A",
        "scheme_context": "Indianapolis Dungy + multiple teams; 4-3 base + 3-4; technique-first rush archetype",
        "signature_trait": "Spin-move technique + bend + first-step quickness",
        "is_fm_reference": 0,
    },

    # -------------------------------------------------------------------------
    # S — 7 records
    # -------------------------------------------------------------------------
    {
        "player_name": "Ed Reed",
        "position": "S",
        "archetype_code": "S-1",
        "mechanism": "Free safety range + instinct prototype; ball-hawk + coverage + run support; elite football IQ",
        "translation_outcome": "HIT",
        "fm_code": None,
        "fm_mechanism": None,
        "outcome_summary": "Hall of Fame; DPOY 2004; all-time INT yards leader; free safety prototype",
        "era_bracket": "2002-2013",
        "peak_years": "2004-2011",
        "comp_confidence": "A",
        "scheme_context": "Baltimore Ravens Rex Ryan; Cover-2 + Cover-4 hybrid; centerfield free safety",
        "signature_trait": "Ball-hawk instincts + range + run-support + coverage awareness",
        "is_fm_reference": 0,
    },
    {
        "player_name": "Tyrann Mathieu",
        "position": "S",
        "archetype_code": "S-3",
        "mechanism": "Multiplier safety; coverage + blitz + run support; versatile deployment across DB alignments",
        "translation_outcome": "HIT",
        "fm_code": None,
        "fm_mechanism": None,
        "outcome_summary": "Multiple All-Pro; Super Bowl champion; Swiss-army DB prototype; multiplier ceiling",
        "era_bracket": "2013-present",
        "peak_years": "2019-2022",
        "comp_confidence": "A",
        "scheme_context": "Kansas City Spagnuolo; multiple alignment use; coverage + blitz + run support",
        "signature_trait": "Multiplier versatility + blitz instincts + coverage range",
        "is_fm_reference": 0,
    },
    {
        "player_name": "Marcus Williams",
        "position": "S",
        "archetype_code": "S-1",
        "mechanism": "Range + coverage free safety; centerfield ball-hawk; missed tackle liability documented",
        "translation_outcome": "HIT",
        "fm_code": None,
        "fm_mechanism": None,
        "outcome_summary": "Pro Bowl; $70M contract; range-coverage free safety value realized despite tackle concerns",
        "era_bracket": "2017-present",
        "peak_years": "2021-2024",
        "comp_confidence": "B",
        "scheme_context": "New Orleans/Baltimore; centerfield role; coverage + ball-hawk primary mechanism",
        "signature_trait": "Range + ball-hawk + coverage without run-support reliability",
        "is_fm_reference": 0,
    },
    {
        "player_name": "Kam Chancellor",
        "position": "S",
        "archetype_code": "S-2",
        "mechanism": "Box safety enforcer; physical-first run-stop + coverage; physical presence as primary tool",
        "translation_outcome": "HIT",
        "fm_code": None,
        "fm_mechanism": None,
        "outcome_summary": "3× All-Pro; Legion of Boom anchor; physical-first box safety prototype",
        "era_bracket": "2010-2017",
        "peak_years": "2012-2017",
        "comp_confidence": "A",
        "scheme_context": "Seattle Carroll Cover-3; strong safety box role; physical enforcement primary",
        "signature_trait": "Run-stop physicality + coverage presence + big-hit intimidation",
        "is_fm_reference": 0,
    },
    {
        "player_name": "Jamal Adams",
        "position": "S",
        "archetype_code": "S-2",
        "mechanism": "Box safety blitz machine; elite run-stop + blitz production; coverage ceiling limited",
        "translation_outcome": "MISS",
        "fm_code": "FM-3",
        "fm_mechanism": "Context Dependency — blitz-specialist box safety traded for massive resources; run/blitz value real but coverage gap constrained role to scheme-specific deployment",
        "outcome_summary": "2-first-round trade; injuries + coverage limitations suppressed value; box-blitz specialist only",
        "era_bracket": "2017-present",
        "peak_years": "2019-2020",
        "comp_confidence": "A",
        "scheme_context": "New York Jets/Seattle; blitz-package specialist; coverage limitations consistent",
        "signature_trait": "Elite blitz + run-stop without coverage ceiling to match cost",
        "is_fm_reference": 0,
    },
    {
        "player_name": "Minkah Fitzpatrick",
        "position": "S",
        "archetype_code": "S-3",
        "mechanism": "Multiplier safety; elite coverage range + blitz + run support; DB versatility realized",
        "translation_outcome": "HIT",
        "fm_code": None,
        "fm_mechanism": None,
        "outcome_summary": "2× All-Pro; Steelers centerpiece; multiplier safety ceiling fully realized",
        "era_bracket": "2018-present",
        "peak_years": "2020-2024",
        "comp_confidence": "A",
        "scheme_context": "Pittsburgh Steelers Butler; multiple alignment; ball-hawk + coverage + support",
        "signature_trait": "Multiplier versatility + range + INT production + coverage IQ",
        "is_fm_reference": 0,
    },
    {
        "player_name": "Kyle Hamilton",
        "position": "S",
        "archetype_code": "S-3",
        "mechanism": "Size-athleticism multiplier; coverage + run-stop + blitz; generational S measurables",
        "translation_outcome": "HIT",
        "fm_code": None,
        "fm_mechanism": None,
        "outcome_summary": "Immediate impact Baltimore; All-Pro trajectory; size-multiplier safety prototype",
        "era_bracket": "2022-present",
        "peak_years": "2023-present",
        "comp_confidence": "A",
        "scheme_context": "Baltimore Harbaugh; 2-high + quarters; size-coverage multiplier deployment",
        "signature_trait": "Size + athleticism + coverage range + run-stop physicality",
        "is_fm_reference": 0,
    },
]


# ---------------------------------------------------------------------------
# Seed logic
# ---------------------------------------------------------------------------

def backup_db() -> Path:
    BACKUP_DIR.mkdir(parents=True, exist_ok=True)
    ts = datetime.now().strftime("%Y%m%d_%H%M%S")
    dest = BACKUP_DIR / f"draftos_pre_position_batch2_{ts}.sqlite"
    shutil.copy2(DB_PATH, dest)
    return dest


def seed_records(apply: bool) -> None:
    inserted = 0
    skipped = 0

    conn = sqlite3.connect(DB_PATH)
    conn.row_factory = sqlite3.Row
    try:
        for rec in POSITION_RECORDS:
            if not apply:
                # Check if would insert or skip
                exists = conn.execute(
                    "SELECT 1 FROM historical_comps WHERE player_name=? AND archetype_code=?",
                    (rec["player_name"], rec["archetype_code"]),
                ).fetchone()
                if exists:
                    skipped += 1
                else:
                    inserted += 1
                continue

            conn.execute(
                """
                INSERT OR IGNORE INTO historical_comps (
                    player_name, position, archetype_code,
                    mechanism, translation_outcome,
                    fm_code, fm_mechanism,
                    outcome_summary, era_bracket, peak_years,
                    comp_confidence, scheme_context, signature_trait,
                    is_fm_reference
                ) VALUES (
                    :player_name, :position, :archetype_code,
                    :mechanism, :translation_outcome,
                    :fm_code, :fm_mechanism,
                    :outcome_summary, :era_bracket, :peak_years,
                    :comp_confidence, :scheme_context, :signature_trait,
                    :is_fm_reference
                )
                """,
                rec,
            )
            changed = conn.execute("SELECT changes()").fetchone()[0]
            if changed > 0:
                inserted += 1
            else:
                skipped += 1

        if apply:
            conn.commit()
    finally:
        conn.close()

    mode = "APPLY" if apply else "DRY RUN"
    print(f"[{mode}] inserted={inserted}  skipped(duplicate)={skipped}  total={len(POSITION_RECORDS)}")

    if apply:
        # Verification breakdown
        conn2 = sqlite3.connect(DB_PATH)
        rows = conn2.execute(
            """
            SELECT position, COUNT(*) cnt
            FROM historical_comps
            WHERE is_fm_reference = 0
            GROUP BY position ORDER BY position
            """
        ).fetchall()
        conn2.close()
        print("\nPosition comp counts (is_fm_reference=0):")
        for r in rows:
            print(f"  {r[0]}: {r[1]}")


def main() -> None:
    parser = argparse.ArgumentParser(description="Seed position comps batch 2 (RB/TE/OT/OG/C/IDL/ILB/OLB/S)")
    parser.add_argument("--apply", type=int, default=0, choices=[0, 1],
                        help="0=dry run (default), 1=write to DB")
    args = parser.parse_args()

    apply = bool(args.apply)

    if apply:
        bak = backup_db()
        print(f"Backup: {bak}")

    seed_records(apply)


if __name__ == "__main__":
    main()
