"""
seed_fm_reference_comps.py

Seeds the 36 FM reference historical comp records from
DraftOS_HistoricalComps_FM[1-6]_Reference.docx files into the
historical_comps table, after applying Migration 0046.

Usage:
  python scripts/seed_fm_reference_comps.py --apply 0   # dry run
  python scripts/seed_fm_reference_comps.py --apply 1   # apply

Idempotent: uses INSERT OR IGNORE on (player_name, fm_code).
Backup created automatically before any write.
"""

import argparse
import sqlite3
import shutil
import datetime
from pathlib import Path

# ---------------------------------------------------------------------------
# CONFIG
# ---------------------------------------------------------------------------
DB_PATH     = Path(r"C:\DraftOS\data\edge\draftos.sqlite")
BACKUP_DIR  = Path(r"C:\DraftOS\data\edge\backups")
MIGRATION_NAME = "0046_historical_comps_fm_seed"
MIGRATION_SQL  = Path(r"C:\DraftOS\draftos\db\migrations\0046_historical_comps_fm_seed.sql")

# ---------------------------------------------------------------------------
# FM REFERENCE RECORDS — all 36 records hardcoded from source docs
# ---------------------------------------------------------------------------
# Schema: player_name, position, archetype_code, mechanism, translation_outcome,
#         fm_code, fm_mechanism, outcome_summary, era_bracket, peak_years,
#         comp_confidence, scheme_context, signature_trait, pre_draft_signal,
#         is_fm_reference
# ---------------------------------------------------------------------------

FM_RECORDS = [

    # ── FM-1: ATHLETICISM MIRAGE (6 records) ───────────────────────────────
    {
        "player_name": "Vernon Hargreaves III",
        "position": "CB",
        "archetype_code": "CB-3",
        "mechanism": "Physical press dominance and length-speed combination that produced elite college production against developmental route runners. At Florida, Hargreaves neutralized receivers through a closing-speed advantage. The mechanism had no processing component — when the speed advantage disappeared against NFL-caliber route runners, there was no technique or processing structure to replace it.",
        "translation_outcome": "MISS",
        "fm_code": "FM-1",
        "fm_mechanism": "Athleticism Mirage: College speed advantage of 0.08+ seconds over SEC competition did not transfer. NFL receivers run 4.42. Hargreaves ran 4.50. The coverage that looked like press dominance was reactive pursuit with a closing-speed edge — remove the edge and the mechanism does not exist. No technique structure was present to compensate.",
        "outcome_summary": "CB-3 FM-1 primary bust: combine quickness masked absence of anticipatory processing; NFL speed gap closed, coverage mechanism did not survive; Round 1 Pick 11 capital returned zero starter-level production.",
        "era_bracket": "2016-present",
        "peak_years": "None at NFL starter level",
        "comp_confidence": "A",
        "scheme_context": "Tampa Bay Buccaneers (multiple coordinators, press and zone-heavy schemes). No scheme resolved the absence of a sustainable coverage mechanism.",
        "signature_trait": "The 2016 pre-draft projection package — four consecutive clips of physical press coverage with tight hips and closing speed — that read as CB-3 with CB-1 potential. The same technique in NFL Week 5 against a receiver running 4.42 showed the underlying mechanism: reactive, not anticipatory, speed-dependent, not technique-based.",
        "pre_draft_signal": "MISSED: Florida 4.02 short shuttle (elite quickness) masked 4.50 40-yard dash (functional, not elite for the position). Technique was physical-dominant rather than technique-dominant — hand placement was inconsistent in press reps against post-snap releases. No confirmed anticipatory tendencies on tape; all production was reactive with a speed advantage doing the work. NFL-grade assessment should have flagged: speed advantage = 0.08 seconds faster than Florida competition; NFL speed advantage = 0.00.",
        "is_fm_reference": 1,
    },
    {
        "player_name": "Gareon Conley",
        "position": "CB",
        "archetype_code": "CB-3",
        "mechanism": "Ohio State CB with elite athletic testing (4.35 40, elite RAS) whose college production was generated by raw physical tools against Big Ten competition that did not adequately stress his reactive coverage tendency. The mechanism was physical-dominant with no confirmed processing layer.",
        "translation_outcome": "MISS",
        "fm_code": "FM-1",
        "fm_mechanism": "Athleticism Mirage: 4.35 speed and elite RAS created a draft-room projection ceiling based on physical tools. The mechanism confirmation step — does processing develop to sustain coverage when the speed advantage closes? — was skipped. NFL receivers at 4.40 collapsed the closing-speed edge; no processing layer existed to replace it.",
        "outcome_summary": "CB-3 FM-1 bust: elite combine metrics priced as mechanism confirmation; processing never developed beyond reactive baseline; NFL speed advantage zero at Round 1 capital — the canonical Conley Warning case now embedded in the CB evaluation framework.",
        "era_bracket": "2017-present",
        "peak_years": "2019 (functional, Oakland)",
        "comp_confidence": "A",
        "scheme_context": "Oakland Raiders, Houston Texans, Las Vegas Raiders. Multiple defensive coordinators and scheme families attempted to maximize the physical profile. None resolved the processing absence.",
        "signature_trait": "The combine workout — 4.35 speed, fluid hips, elite short-area quickness — that drove a Round 1 Pick 24 selection and then the NFL tape reality: separation allowed on routes where the receiver simply ran a clean stem with a double-move finish, the exact technique class Conley's processing never handled.",
        "pre_draft_signal": "MISSED: Q4 reactive processing was never confirmed as transitioning to anticipatory. Draft community read his 4.35 speed and 89.4 RAS as ceiling indicators rather than ceiling inputs. Technique off the line showed hesitation against double-move stems at Ohio State — visible on tape against Michigan 2016. Capital was priced at the combine number, not the mechanism confirmation.",
        "is_fm_reference": 1,
    },
    {
        "player_name": "Tavon Austin",
        "position": "WR",
        "archetype_code": "WR-2",
        "mechanism": "West Virginia WR whose 4.28 speed produced an extreme college production environment in a spread offense that manufactured vertical separation before the snap through alignment and motion. Route architecture was minimal — routes were stems to destinations, not stems with shape.",
        "translation_outcome": "MISS",
        "fm_code": "FM-1",
        "fm_mechanism": "Athleticism Mirage: 4.28 speed created a separation advantage against college cornerbacks that did not exist against NFL corners running 4.38. The route architecture that was supposed to be the secondary mechanism was never present at the college level and never developed in the NFL. FM-6 co-activated when the Rams attempted to deploy Austin as a true WR2 rather than as a gadget piece.",
        "outcome_summary": "WR-2 FM-1 primary bust: 4.28 speed priced as separation mechanism; route architecture absent at draft and never developed; Round 1 Pick 8 capital returned gadget snaps, not WR production — the definitive speed-premium overvaluation case.",
        "era_bracket": "2013-2019",
        "peak_years": "2013 (manufactured production, St. Louis)",
        "comp_confidence": "A",
        "scheme_context": "St. Louis/LA Rams (Jeff Fisher era, then Sean McVay early). McVay's YAC-friendly system came too late and the speed had already declined.",
        "signature_trait": "The 2013 Week 1 three-touchdown game — two jet sweeps and a punt return — that looked like WR-2 activation but was actually gadget deployment masking the absence of a sustainable coverage-beating mechanism.",
        "pre_draft_signal": "MISSED: 4.28 speed consumed the evaluation — every scouting report listed the speed first and the route tree second or not at all. West Virginia's Air Raid manufactured open space before the ball was thrown. Austin's contested catch percentage in college was below 40%, invisible against the speed narrative. The mechanism test — does this WR win when the speed advantage compresses in the NFL? — was not applied. Round 1 Pick 8 capital was priced on the 4.28 number, not on the mechanism.",
        "is_fm_reference": 1,
    },
    {
        "player_name": "Dion Jordan",
        "position": "EDGE",
        "archetype_code": "EDGE-2",
        "mechanism": "Oregon EDGE with elite athletic profile (6-6, 248 lbs, elite bend) whose college production was generated almost entirely by athleticism advantages in a scheme that created 1-on-1 opportunities without requiring hand technique. No counter package was developed. First-step athleticism is not a pass rush mechanism; it is the delivery vehicle for a mechanism.",
        "translation_outcome": "MISS",
        "fm_code": "FM-1",
        "fm_mechanism": "Athleticism Mirage: Elite bend and first-step athleticism simulated a pass rush mechanism in college by creating arc-path opportunities that tackles at the college level could not anchor against. NFL tackles neutralized the arc move consistently; no counter move existed to force a different response. FM-4 co-activated with three significant injuries across his career.",
        "outcome_summary": "EDGE-2 FM-1 primary bust: elite athleticism and bend at the combine priced as pass rush mechanism; no counter package ever developed; Round 1 Pick 3 capital returned six career sacks — the definitive physical-projection-without-mechanism case at EDGE.",
        "era_bracket": "2013-2019",
        "peak_years": "2016 (Seattle, 6.5 sacks — brief functional window)",
        "comp_confidence": "A",
        "scheme_context": "Miami Dolphins, Seattle Seahawks, multiple teams. No coordinator was able to manufacture a sustainable deployment structure because no underlying mechanism existed to deploy.",
        "signature_trait": "The Combine workout — elite bend test, arm length, explosion scores — that generated the 'next great pass rusher' consensus and the Round 1 Pick 3 capital investment, followed by the NFL tape reality of a tackle loading against the arc and Jordan having no answer.",
        "pre_draft_signal": "MISSED: Elite bend (hip flexibility) was mistaken for a pass rush mechanism. The mechanism test — what does he do when the tackle takes the arc away? — produced no answer from Oregon tape. Counter development was absent; hand sequence was underdeveloped; plan B off the initial burst did not exist. Round 1 Pick 3 capital was priced on physical projection, not confirmed mechanism.",
        "is_fm_reference": 1,
    },
    {
        "player_name": "Mike Williams (2010)",
        "position": "WR",
        "archetype_code": "WR-3",
        "mechanism": "USC WR whose 6-2 physical profile and burst metrics produced an elite YAC grade in college when operating against single-high coverage with space after the catch. Williams' college YAC was primarily scheme-generated: USC's spacing concepts created lanes that made post-catch YAC look like a player ability when it was a coverage situation.",
        "translation_outcome": "MISS",
        "fm_code": "FM-1",
        "fm_mechanism": "Athleticism Mirage: Physical profile (size + speed) simulated a WR-3 separation mechanism that was actually scheme-generated open-space production. NFL defensive structures closed the manufactured lanes consistently; player-generated YAC mechanism was insufficient to sustain production. FM-2 activated as career continued — production became almost entirely system-dependent.",
        "outcome_summary": "WR-3 FM-1 primary bust: physical size-speed profile and scheme-generated YAC priced as player mechanism; NFL defensive sophistication closed manufactured lanes; Day 2 capital returned one functional season, confirming YAC audit is mandatory before WR-3 capital assignment.",
        "era_bracket": "2010-2016",
        "peak_years": "2010 (Tampa Bay — 964 yards, but contested catch rate below 45%)",
        "comp_confidence": "B",
        "scheme_context": "Tampa Bay Buccaneers (Raheem Morris era), multiple teams after. Production collapsed immediately when USC's spacing concepts were unavailable.",
        "signature_trait": "The 2009 USC tape showing consecutive games with 100+ yards and 4+ catches against single-high coverage with vacated intermediate zones — followed by the NFL reality of a WR who required specific spacing to function.",
        "pre_draft_signal": "MISSED: Size-speed combination (6-2, 4.43) was read as the mechanism. The PAA equivalent for the era — does this YAC come from the player or from the scheme? — was not applied. College YAC breakdown by coverage type was not conducted. The scheme-generated YAC proportion was above 60% but invisible beneath the aggregate number.",
        "is_fm_reference": 1,
    },
    {
        "player_name": "Robert Quinn",
        "position": "EDGE",
        "archetype_code": "EDGE-2",
        "mechanism": "North Carolina EDGE who presented FM-1 risk indicators at draft (speed-arc primary, hand technique underdeveloped) but whose NFL development confirmed the mechanism extended beyond athleticism. Quinn's hand sequencing developed in Year 2-3: a counter inside move off the arc loaded opposite response allowed him to sustain production as first-step burst declined with age.",
        "translation_outcome": "HIT",
        "fm_code": "FM-1",
        "fm_mechanism": "N/A — FM-1 risk did not activate. Counter package development (inside counter off arc read) extended the mechanism beyond the athleticism window. RESOLUTION CASE: FM-1 risk present pre-draft, resolved through development.",
        "outcome_summary": "EDGE-2 FM-1 risk resolved through development: arc-speed primary with underdeveloped counter pre-draft, counter confirmed by Year 3, All-Pro ceiling reached — the reference case for EDGE-2 FM-1 risk that develops versus risk that does not.",
        "era_bracket": "2011-2021",
        "peak_years": "2013-2014, 2019",
        "comp_confidence": "A",
        "scheme_context": "St. Louis Rams (Jeff Fisher, aggressive edge system), Dallas Cowboys, Chicago Bears, Philadelphia Eagles. Production sustained across multiple scheme families, confirming system-transcendent mechanism once counter was added.",
        "signature_trait": "The 2013 season — 19 sacks, first-team All-Pro — where Quinn's counter move off the loaded-outside tackle response produced a complete pass rush mechanism that the pre-draft evaluation had correctly identified as absent but which development confirmed.",
        "pre_draft_signal": "FM-1 RISK PRESENT AND IDENTIFIED: 2011 draft evaluation noted hand technique as underdeveloped and arc-move dependent. The differentiation from Jordan (2013) is the outcome: Quinn showed counter development in Year 2-3 that Jordan never showed. The pre-draft signal was the same; the developmental response was different. This case establishes the DraftOS principle: FM-1 risk at EDGE-2 does not equal FM-1 bust.",
        "is_fm_reference": 1,
    },

    # ── FM-2: SCHEME GHOST (7 records) ─────────────────────────────────────
    {
        "player_name": "Marcus Peters",
        "position": "CB",
        "archetype_code": "CB-2",
        "mechanism": "Washington CB whose zone coverage production was genuine and elite: QB-read processing in zone concepts allowed him to generate interceptions at a rate that exceeded any corner of his era in the right scheme. The structural problem was the man coverage floor: Peters could not reliably execute press-man coverage against route runners who required physical disruption at the line.",
        "translation_outcome": "PARTIAL",
        "fm_code": "FM-2",
        "fm_mechanism": "Scheme Ghost — zone processing excellence confirmed but not transferable to man coverage contexts. The cognitive mechanism that made Peters elite in zone (QB-read positioning, anticipatory throwing-lane occupation) did not apply when the task switched to individual receiver tracking. NFL offensive coordinators identified the man coverage floor within two seasons and built targeted attack structures around it.",
        "outcome_summary": "CB-2 FM-2 structural partial: zone processing excellence produced elite peak but man coverage floor absence was systematically exploited; career value compressed to scheme-dependent range; confirms man coverage floor is the single most important capital determinant for the CB-2 archetype.",
        "era_bracket": "2015-present",
        "peak_years": "2015-2018",
        "comp_confidence": "A",
        "scheme_context": "Kansas City Chiefs (zone-heavy, Alex Smith era — peak production), Los Angeles Rams (McVay zone-friendly — sustained), Baltimore Ravens (Wink Martindale mixed — partial). Production correlated directly with zone usage rate across every team.",
        "signature_trait": "The 2015-2016 interception production in Kansas City's zone scheme — 8 interceptions in 20 games — followed by the repeated NFL tape pattern where man coverage assignments produced separation against Peters that zone assignments never allowed.",
        "pre_draft_signal": "VISIBLE AND DOCUMENTED: Washington's zone-heavy system in 2014-2015 generated turnover production that masked the man coverage floor absence. Pre-draft scouting noted technique concerns in press-man reps — hip rotation in press was late, transition off the line was hesitant when receivers attacked vertically in man. NFL teams that ran heavy man-coverage schemes (New England, Pittsburgh) targeted Peters systematically in man reps throughout his career.",
        "is_fm_reference": 1,
    },
    {
        "player_name": "Antrel Rolle",
        "position": "S",
        "archetype_code": "S-3",
        "mechanism": "Arizona Cardinals safety whose single-high zone range and ball-hawking production in Cover-3 and Cover-1 shell looks created a genuine S-2 Centerfielder production record in college and early NFL. The failure mode was the post-snap assignment adjustment gap — the S-3 Multiplier capability that the draft evaluation projected onto his zone range profile was never confirmed.",
        "translation_outcome": "PARTIAL",
        "fm_code": "FM-2",
        "fm_mechanism": "Scheme Ghost — scripted zone versatility misread as genuine post-snap assignment flexibility. Rolle's production was real within his operating parameters: pre-scripted zone assignments, single-high shell looks, defined coverage responsibilities. The S-3 Multiplier projection that drove Round 1 capital required a post-snap adjustment mechanism that was never present.",
        "outcome_summary": "S FM-2 structural partial: pre-scripted zone excellence real, post-snap assignment adjustment absent, S-3 Multiplier projection never confirmed; career compressed to zone-scheme dependency; the canonical safety FM-2 case and direct warning against projecting multiplier versatility from zone production volume.",
        "era_bracket": "2005-2014",
        "peak_years": "2009-2012",
        "comp_confidence": "A",
        "scheme_context": "Arizona Cardinals (Ken Whisenhunt zone-heavy — best production), New York Giants (Perry Fewell mixed — functional), Chicago Bears (late career — below threshold). Zone usage rate and production output correlated consistently across every team.",
        "signature_trait": "The Arizona 2009 run — 5 interceptions, Pro Bowl — in Whisenhunt's pre-scripted zone structure, followed by the Giants tape where motion-heavy offenses pre-snap forced Rolle into post-snap assignment reads he could not process.",
        "pre_draft_signal": "MISSED — PROJECTION ERROR: Iowa's secondary scheme in 2004-2005 ran heavy Cover-2 and Cover-3 with pre-scripted safety assignments. Post-snap adjustment reps were minimal in the college system. Draft evaluation projected S-3 versatility from zone excellence without confirming post-snap adjustment on tape. The mechanism confirmation step — does this safety change assignments based on offensive deployment after the snap, or does he execute the pre-scripted assignment? — was not conducted.",
        "is_fm_reference": 1,
    },
    {
        "player_name": "Bashaud Breeland",
        "position": "CB",
        "archetype_code": "CB-2",
        "mechanism": "Clemson CB whose zone production in a scheme-friendly system generated coverage grades that read as CB-2 confirmation but were structurally scheme-dependent. The QB-read processing that defines CB-2 was present in Clemson's zone concepts — Breeland positioned correctly in pre-scripted zone assignments against ACC competition. The mechanism was not confirmed in man coverage reps.",
        "translation_outcome": "MISS",
        "fm_code": "FM-2",
        "fm_mechanism": "Scheme Ghost — CB-2 archetype assigned from zone production without man coverage floor confirmation. NFL teams ran man coverage against Breeland from Year 1; the zone concept reading mechanism did not transfer to individual receiver tracking. Career was a series of short contracts with teams that ran zone-heavy systems when production was functional.",
        "outcome_summary": "CB-2 FM-2 structural miss: zone production in a zone-heavy system assigned CB-2 archetype without man coverage floor confirmation; man coverage exploitation began Year 1 in NFL; career nomadic and below starter threshold across multiple teams.",
        "era_bracket": "2014-2022",
        "peak_years": "2017 (Washington Redskins — zone-aligned)",
        "comp_confidence": "A",
        "scheme_context": "Washington Redskins (zone-friendly, best production), Green Bay Packers (mixed), Kansas City Chiefs (zone-favorable), multiple short stints. Every production uptick correlated with increased zone usage.",
        "signature_trait": "The 2017 Washington tape showing consistent zone positioning and coverage wins — followed by the Packers tape one year later showing the exact same alignment packages producing the exact opposite result when man coverage assignments required individual receiver tracking.",
        "pre_draft_signal": "MISSED: Clemson's zone-heavy system in 2013-2014 did not generate the man coverage rep volume required for CB-2 man floor confirmation. Pre-draft scouting noted limited man coverage exposure but did not apply the DraftOS rule: a CB-2 without confirmed man coverage floor (Grade 60+ in man situations) has structural FM-2 exposure that no scheme can resolve. Zone production in a zone-heavy system without man confirmation is CB-3 or CB-5, not CB-2.",
        "is_fm_reference": 1,
    },
    {
        "player_name": "Adoree Jackson",
        "position": "CB",
        "archetype_code": "CB-2",
        "mechanism": "USC CB and return specialist whose college production was divided between coverage reps (zone-heavy scheme) and return value (special teams speed). The CB-2 zone processing projection was made from limited coverage reps in a scheme that did not stress man coverage. The mechanism was speed-to-positioning in zone — not zone processing.",
        "translation_outcome": "PARTIAL",
        "fm_code": "FM-2",
        "fm_mechanism": "Scheme Ghost — zone coverage reps in a coverage-light college system generated CB-2 projection that was not mechanism-confirmed. NFL teams targeted Jackson in man coverage from Year 1 in Tennessee. Zone processing development under Mike Vrabel and later Dave Canales eventually produced a functional CB-2 outcome, but the man coverage floor remained inconsistent through Year 4.",
        "outcome_summary": "CB-2 FM-2 partial: college scheme did not generate coverage rep volume for CB-2 confirmation; first three NFL seasons showed man coverage floor inconsistency; functional CB-2 emerged in Year 5+ but career value compressed by early exploitation.",
        "era_bracket": "2017-present",
        "peak_years": "2021-2023",
        "comp_confidence": "A",
        "scheme_context": "Tennessee Titans (multiple coordinators — inconsistent deployment), New York Giants (Wink Martindale zone-friendly — production uptick). Man coverage usage rate and production quality anti-correlated across his career.",
        "signature_trait": "The 2017 Tennessee deployment — CB2 starter role in a mixed coverage scheme — that revealed the man coverage floor within the first six weeks and produced the targeted exploitation pattern that defined the first three years of his career.",
        "pre_draft_signal": "VISIBLE: USC's coverage system gave Jackson 60%+ zone reps with alignment-based positioning, not QB-read processing. Man coverage reps against top WR competition in 2016 showed hip transition hesitation against double-move routes — the same tell as Hargreaves and Peters, documented in pre-draft scouting and then ignored. Return value inflated draft capital above mechanism-confirmed CB ceiling.",
        "is_fm_reference": 1,
    },
    {
        "player_name": "Jordan Howard (EDGE — Wide 9)",
        "position": "EDGE",
        "archetype_code": "EDGE-2",
        "mechanism": "Wide-9 scheme amplification case — production generated by alignment advantage (outside shade creating leverage) rather than confirmed hand-to-hand pass rush mechanics. Wide-9 EDGE prospects in 4-3 systems with natural outside leverage create production environments that project as EDGE-2 Speed Rusher when the underlying mechanism is scheme-position, not rush development.",
        "translation_outcome": "MISS",
        "fm_code": "FM-2",
        "fm_mechanism": "Scheme Ghost — wide-9 alignment manufactured outside leverage that simulated pass rush mechanism. When NFL teams reduced the alignment advantage through tackle technique adjustment and tight alignment, the manufactured production disappeared. No hand-to-hand counter mechanism existed to replace the alignment leverage.",
        "outcome_summary": "EDGE-2 FM-2 bust via scheme amplification: wide-9 production without confirmed hand-technique mechanism; NFL tackles neutralized alignment leverage; production below starter threshold across career; confirms wide-9 EDGE prospects require mandatory scheme-amplification audit.",
        "era_bracket": "2018-2024",
        "peak_years": "2018-2019 (scheme-generated)",
        "comp_confidence": "B",
        "scheme_context": "Multiple teams across 4-3 and 3-4 base systems. Production only functional in wide-9 or reduced tackle sets. Hand-to-hand reps against NFL-caliber tackles produced consistent stalemates.",
        "signature_trait": "The college pass rush tape — consecutive clips of first-step burst converting to sack opportunities — that reads as EDGE-2 mechanism but on rewatch shows outside leverage from wide-9 alignment doing the work, not hand sequence.",
        "pre_draft_signal": "MISSED: Wide-9 system audit was not conducted. Scheme-amplification ratio — what percentage of production required the alignment advantage? — was above 60% but not calculated. Hand-technique reps against tight-set tackles (simulating NFL tackle technique) showed stalemate pattern. The mechanism test — what does this EDGE do against a tackle who takes the outside away and plays the arc? — produced no answer from college tape.",
        "is_fm_reference": 1,
    },
    {
        "player_name": "Richard Sherman",
        "position": "CB",
        "archetype_code": "CB-2",
        "mechanism": "Stanford CB whose zone coverage production was genuine QB-read processing, not coverage-family-dependent positioning. Sherman's interception production in Pete Carroll's Cover-3 scheme was mechanism-confirmed: pre-snap QB identification, route stem recognition, and throwing-lane occupation that transferred across coverage families. The zone was the expression, not the mechanism.",
        "translation_outcome": "HIT",
        "fm_code": "FM-2",
        "fm_mechanism": "N/A — FM-2 did not activate. QB-read processing confirmed as coverage-family-agnostic. Not rep-count-specific. RESOLUTION CASE: The CB-2 FM-2 non-activation criteria. Resolution is mechanism-specific: QB-read processing confirmed as coverage-family-agnostic.",
        "outcome_summary": "CB-2 FM-2 risk resolved: zone production confirmed as QB-read mechanism rather than scheme-dependent positioning; man coverage floor confirmed pre-draft through limited but high-quality reps; Hall of Fame career across zone and man coverage families — the resolution reference case for CB-2 FM-2 evaluation.",
        "era_bracket": "2011-2018",
        "peak_years": "2012-2016",
        "comp_confidence": "A",
        "scheme_context": "Seattle Seahawks (Carroll Cover-3 — elite production), San Francisco 49ers (Robert Saleh mixed — functional). Production maintained across zone and man coverage contexts once the processing mechanism was confirmed.",
        "signature_trait": "The 2013 NFC Championship tip — reading Crabtree's release stem, identifying the route family, breaking on the throw before the ball arrived — that confirmed anticipatory processing rather than reactive coverage. The mechanism was QB-read, not scheme positioning.",
        "pre_draft_signal": "FM-2 RISK NOT PRESENT: Stanford's 2010 tape showed man coverage reps where Sherman read release stems and transitioned cleanly — low volume but high quality. Pre-draft confirmation: man floor present at Grade 62 equivalent. The DraftOS principle confirmed: man floor confirmation in limited reps is sufficient if the mechanism is QB-read, not coverage-family-specific positioning.",
        "is_fm_reference": 1,
    },

    # ── FM-3: PROCESSING WALL (6 records) ──────────────────────────────────
    {
        "player_name": "JaMarcus Russell",
        "position": "QB",
        "archetype_code": "QB-5",
        "mechanism": "LSU QB with elite arm talent and physical projection profile — 6-6, 265 lbs, with velocity that no pre-draft evaluation had seen at the position. The mechanism was arm-to-velocity: Russell's raw delivery created production opportunities in college through physical advantage that did not require full-field processing. The processing mechanism required to sustain performance at NFL complexity was never confirmed.",
        "translation_outcome": "MISS",
        "fm_code": "FM-3",
        "fm_mechanism": "Processing Wall: Could not execute full-field reads under pressure against NFL complexity. College production was designed-play dominant — the LSU system minimized read requirements. No confirmed progression read on tape. FM-5 co-activated post-contract, compounding the FM-3 bust through organizational decisions made on the back of the physical projection.",
        "outcome_summary": "QB-5 FM-3 and FM-5 compound bust: elite arm talent priced as processing mechanism; full-field reads never confirmed at NFL complexity; motivation cliff post-contract accelerated collapse; Round 1 Pick 1 capital returned 7 career wins — the single most expensive bust in the database and the primary QB-2/QB-5 compound FM warning.",
        "era_bracket": "2007-2010",
        "peak_years": "None at NFL starter level",
        "comp_confidence": "A",
        "scheme_context": "Oakland Raiders (Lane Kiffin, Tom Cable, various). Multiple offensive systems attempted to manufacture QB-read requirements within Russell's processing ceiling. None succeeded.",
        "signature_trait": "The pre-draft workout — velocity readings that exceeded any QB in history, physical dimensions that projected as an All-Pro — followed by the NFL tape reality of a QB who could not identify blitz coverage from Cover-2 shell pre-snap and processed plays reactively rather than diagnostically.",
        "pre_draft_signal": "MISSED: LSU's 2006 playbook minimized pre-snap read requirements. Production came from designed one-read throws (quick game, play-action) and physical domination of college defensive fronts. The mechanism test — full-field progression read against simulated NFL blitz coverage in a controlled pre-draft evaluation — was not conducted or not applied to capital. FM-5 indicators (C2 and C3 concerns documented by multiple teams pre-draft) were present and ignored.",
        "is_fm_reference": 1,
    },
    {
        "player_name": "Blaine Gabbert",
        "position": "QB",
        "archetype_code": "QB-2",
        "mechanism": "Missouri QB in a spread system that manufactured quick-game production and minimized pocket processing requirements. The mechanism was speed-to-throw: Gabbert's release timing in quick game was elite, creating functional production against college competition in a system that did not require pre-snap diagnosis or full-field processing under pressure.",
        "translation_outcome": "MISS",
        "fm_code": "FM-3",
        "fm_mechanism": "Processing Wall: Full-field processing under NFL pocket pressure never confirmed. Gabbert's production in Missouri's quick-game system required neither blitz identification nor progression reads. NFL pressure collapsed the quick-game timing advantage and the absence of a full-field processing mechanism produced immediate and severe regression. Became one of the most pressure-sensitive QBs of his era — the FM-3 signal was the college system design, not the individual.",
        "outcome_summary": "QB-2 FM-3 bust: spread system manufactured quick-game production without confirming full-field processing; NFL pressure immediately exposed the processing ceiling; Round 1 Pick 10 capital returned career journeyman backup production.",
        "era_bracket": "2011-2021",
        "peak_years": "None at NFL starter level",
        "comp_confidence": "A",
        "scheme_context": "Jacksonville Jaguars (Ron Meeks and subsequent coordinators), San Francisco 49ers, multiple teams as backup. No system resolved the processing ceiling because the ceiling was structural, not scheme-dependent.",
        "signature_trait": "The 2011 Jacksonville film showing a QB who processed clean-pocket designed plays at average NFL speed and then collapsed under any blitz pressure — sack rate and pressures-to-turnover ratio that confirmed the processing wall was present in NFL Week 1 and never resolved.",
        "pre_draft_signal": "MISSED: Missouri's spread offense in 2010 ran primarily quick game and play-action. Blitz recognition reps — the diagnostic task that separates QB-1 and QB-2 from QB-5 — were minimal. Pre-draft evaluation focused on arm talent, mobility, and quick-game efficiency. The DraftOS FM-3 detection gate at QB — completion rate and decision quality on designed drop-backs with clean pocket structure — was not applied.",
        "is_fm_reference": 1,
    },
    {
        "player_name": "Johnny Manziel",
        "position": "QB",
        "archetype_code": "QB-2",
        "mechanism": "Texas A&M QB whose improvisation-dominant production created a false ceiling signal — the DraftOS FM-3 critical distinction case. Improvisation is not processing. Manziel's production was improvisation-dominant: designed play breaks down, QB scrambles, generates positive play. The completion rate and decision quality on designed drop-backs with clean pocket structure — the actual FM-3 detection gate — showed a processing ceiling that the improvisation volume obscured.",
        "translation_outcome": "MISS",
        "fm_code": "FM-3",
        "fm_mechanism": "Processing Wall: QB-2 archetype assigned based on improvisation production rather than processing confirmation. Improvisation-dominant QBs fail the FM-3 gate because the mechanism requires a full-field read mechanism, not an escape mechanism. FM-5 compound — motivation cliff activated simultaneously with the processing wall, making the compound bust the most expensive QB evaluation error of the decade.",
        "outcome_summary": "QB-2 FM-3 and FM-5 compound bust: improvisation production misread as processing confirmation; full-field read mechanism absent; motivation cliff post-contract; Round 1 Pick 22 capital returned 8 career starts — the canonical improvisation-vs-processing failure case.",
        "era_bracket": "2014-2018",
        "peak_years": "None at NFL starter level",
        "comp_confidence": "A",
        "scheme_context": "Cleveland Browns (Mike Pettine, then Hue Jackson). Multiple offensive coordinators attempted to replicate the Texas A&M improvisation environment. NFL defensive sophistication closed the escape mechanism faster than any scheme adjustment could address.",
        "signature_trait": "The Heisman Trophy tape — consecutive improvisation plays in the Aggie stadium — that generated the 'Football Jesus' consensus and then the NFL film showing a QB who, on clean-pocket designed drop-backs against NFL blitz coverage, processed at below-starter threshold before escaping the pocket.",
        "pre_draft_signal": "MISSED — CRITICAL DISTINCTION FAILURE: Improvisation volume was read as processing confirmation. The FM-3 detection gate — completion rate and decision quality on designed drop-backs with clean pocket structure — was not calculated separately from improvisation plays. Texas A&M's system generated improvisation opportunities by design. FM-5 indicators (C2 and C3 profile) were present in pre-draft evaluations and minimized.",
        "is_fm_reference": 1,
    },
    {
        "player_name": "Jon Beason",
        "position": "ILB",
        "archetype_code": "ILB-1",
        "mechanism": "Miami LB whose ILB-1 Sideline-to-Sideline mechanism was confirmed at entry NFL complexity: run diagnosis, pursuit angles, and man coverage execution against tight ends were at elite level. The FM-3 sub-classification — ceiling case, not absence case — mechanism present at entry complexity, fails at advanced disguise. Beason's processing ceiling was disguised coverage pre-snap: when offenses began running complex pre-snap motion packages designed to move Beason out of his diagnostic structure, the ceiling became evident.",
        "translation_outcome": "PARTIAL",
        "fm_code": "FM-3",
        "fm_mechanism": "Processing Wall — FM-3 ceiling sub-classification: mechanism present at entry NFL complexity, fails at advanced disguise. Beason's ILB-1 processing was real and elite within its operating range. The ceiling became evident at Year 3 when offensive coordinators began running motion-heavy pre-snap designs that required post-snap assignment adjustment. The mechanism was present; the ceiling was lower than projected.",
        "outcome_summary": "ILB-1 FM-3 ceiling partial: entry-complexity ILB-1 mechanism confirmed and elite; advanced disguise pre-snap processing ceiling reached at Year 3; career value compressed by both FM-3 ceiling and FM-4 injuries; confirms FM-3 at ILB-1 has two distinct sub-profiles requiring different capital implications.",
        "era_bracket": "2007-2014",
        "peak_years": "2007-2010",
        "comp_confidence": "A",
        "scheme_context": "Carolina Panthers (Ron Rivera era, John Fox run-heavy system — best production). Production high in systems where pre-snap disguise was minimal. Regression began when offenses identified the pre-snap adjustment ceiling and attacked it.",
        "signature_trait": "The 2008-2009 Panthers run — 138 tackles per season, sideline-to-sideline range that confirmed ILB-1 mechanism — followed by the 2011-2012 film showing a LB who could not adjust assignments post-snap against motion-heavy packages, producing the coverage breakdowns that defined his decline.",
        "pre_draft_signal": "FM-3 CEILING NOT DETECTED PRE-DRAFT: Miami's 2006 defensive system ran limited pre-snap disguise packages and did not generate advanced coverage assignment reps. ILB-1 mechanism was confirmed at entry complexity. The ceiling sub-classification — can this LB adjust post-snap at advanced disguise complexity? — was not tested. College tape showed no pre-snap assignment adjustment reps. The DraftOS FM-3 ILB sub-classification distinguishes absence from ceiling; the ceiling case requires post-snap adjustment reps in college tape for confirmation.",
        "is_fm_reference": 1,
    },
    {
        "player_name": "Mike Williams (WR, 2005)",
        "position": "WR",
        "archetype_code": "WR-3",
        "mechanism": "USC WR whose size-route combination produced elite college production in a system that designed routes within his processing range. The WR-3 route tree at NFL level requires the ability to execute routes against NFL-caliber press coverage — a processing task (route stem recognition and release adjustment) that is independent of the physical tools used to run the route.",
        "translation_outcome": "MISS",
        "fm_code": "FM-3",
        "fm_mechanism": "Processing Wall at WR-3: inability to execute route tree against NFL-caliber press coverage. The WR-3 mechanism requires reading coverage and adjusting the stem accordingly — a processing task that is independent of the physical tools. Williams' route tree in college was run against developmental defensive backs whose press technique did not require stem adjustment. NFL press coverage with hand fighting at the line produced processing demands the WR-3 mechanism could not meet.",
        "outcome_summary": "WR-3 FM-3 bust: size-route production in college system priced as WR-3 mechanism; NFL press coverage required stem adjustment processing absent at draft and not developed; multiple teams, below starter threshold production — confirms WR-3 route tree execution against NFL press is the non-negotiable mechanism gate.",
        "era_bracket": "2005-2010",
        "peak_years": "2005 (Detroit — scheme-manufactured)",
        "comp_confidence": "A",
        "scheme_context": "Detroit Lions, Buffalo Bills, multiple teams. No offensive coordinator was able to replicate the USC route-design system that eliminated the press processing requirement.",
        "signature_trait": "The USC 2004 tape showing a dominant WR running clean routes against developmental corners in a system designed to get him open — followed by the NFL tape showing the same route tree failing immediately against press coverage that required stem adjustment at the line.",
        "pre_draft_signal": "MISSED: USC's 2004 route design minimized press coverage exposure. The WR-3 mechanism test — does this receiver win against press coverage that requires stem adjustment at the line? — was not conducted with adequate rep volume. College production was dominant but produced against competition that did not generate the route-stem adjustment processing demand that NFL corners require.",
        "is_fm_reference": 1,
    },
    {
        "player_name": "Alex Smith",
        "position": "QB",
        "archetype_code": "QB-1",
        "mechanism": "Utah QB whose FM-3 risk indicators at draft (limited full-field reads in spread system, processing confirmation incomplete) were neutralized by elite C2 and C3 character architecture. The FM-3 resolution criteria case at QB: risk is conditional (not structural) when C2 and C3 character architecture is confirmed elite pre-draft. Smith's work ethic and coachability allowed him to build the full-field processing mechanism post-draft that was not confirmed in college.",
        "translation_outcome": "HIT",
        "fm_code": "FM-3",
        "fm_mechanism": "N/A — FM-3 risk conditional, resolved through C2/C3 character architecture. Smith's Utah spread system did not generate full-field processing reps at adequate volume. However, C2 (motivation/work ethic) and C3 (coachability/psychological profile) were elite — the Schwesinger Rule equivalent for the QB position. FM-3 risk at QB is conditional when C2/C3 is confirmed elite; it is structural when C2/C3 is below threshold.",
        "outcome_summary": "QB-1 FM-3 risk resolved through elite character architecture: spread system limited processing confirmation pre-draft; C2 and C3 profile elite; full-field processing mechanism built in Andy Reid and Greg Knapp systems; long NFL career as functional QB-1 — the definitive FM-3 conditional resolution case at QB.",
        "era_bracket": "2005-2020",
        "peak_years": "2012-2017",
        "comp_confidence": "A",
        "scheme_context": "San Francisco 49ers (Mike Nolan, then Harbaugh — mechanism development), Kansas City Chiefs (Andy Reid — QB-1 peak production), Washington. Production scaled with coaching infrastructure quality — confirming the C2/C3 development trajectory.",
        "signature_trait": "The 2012 San Francisco film under Harbaugh — full-field progression reads executed at starter efficiency in a complex West Coast system — that confirmed the FM-3 processing mechanism had been built post-draft through elite coachability. The pre-draft risk did not activate because the character architecture prevented it.",
        "pre_draft_signal": "FM-3 RISK CONDITIONAL — NOT STRUCTURAL: Utah's spread system in 2004 generated limited full-field read reps. FM-3 risk indicators present. Resolution criteria confirmed: C2 (work ethic) rated elite across all pre-draft contacts. C3 (psychological profile and coachability) confirmed elite. Without C2/C3 confirmation, FM-3 risk at QB should be treated as structural regardless of physical ceiling. With C2/C3 confirmed elite, risk is conditional and development-dependent.",
        "is_fm_reference": 1,
    },

    # ── FM-4: BODY BREAKDOWN (8 of 16 records — highest confidence) ────────
    {
        "player_name": "Bo Jackson (NFL)",
        "position": "RB",
        "archetype_code": "RB-1",
        "mechanism": "Auburn RB with a physical mechanism that existed entirely in a different category from any contemporary — speed, power, and elusiveness at a combination that has not been replicated. The FM-4 case is not a bust case — it is the definitive availability case: what happens when the highest-ceiling mechanism in the database is removed by injury in Year 3. The mechanism was real and confirmed. The body could not sustain it.",
        "translation_outcome": "PARTIAL",
        "fm_code": "FM-4",
        "fm_mechanism": "Body Breakdown FM-4a — structural/orthopedic. Hip injury (acetabular avascular necrosis) in Year 3 ended a career that, by production rate over healthy games, was projecting as the highest-ceiling RB in NFL history. The FM-4 lesson: mechanism confirmation is necessary but not sufficient when the physical mechanism is joint-dependent. Hip health is the primary FM-4 gate at RB for physical-mechanism archetypes.",
        "outcome_summary": "RB-1 FM-4a catastrophic: highest-ceiling RB mechanism in database, career ended Year 3 by hip injury; 515 career carries in available seasons projecting to 2,000+ career yards per season; the definitive availability case and primary FM-4 calibration anchor for physical-mechanism RBs.",
        "era_bracket": "1987-1990",
        "peak_years": "1987-1990 (3 seasons)",
        "comp_confidence": "A",
        "scheme_context": "Los Angeles Raiders (Mike Shanahan, then Art Shell). Production in limited deployment (baseball dual-sport) was still the highest peak of his era. Scheme was irrelevant — mechanism was player-generated and system-transcendent.",
        "signature_trait": "The 1987 Monday Night Football run against the Seattle Seahawks — 91 yards, multiple broken tackles, acceleration through the secondary that produced a 4.12 electronic timing — that represents the highest single-play mechanism expression in the RB database, followed by the 1991 hip injury that terminated the mechanism permanently.",
        "pre_draft_signal": "FM-4 NOT PRE-DRAFT DETECTABLE: No pre-draft structural indicator of hip vulnerability. FM-4a in this case was traumatic (contact-induced avascular necrosis), not predictable from pre-draft physical structure. The DraftOS implication: FM-4a traumatic cases are not pre-draft detectable. FM-4a structural cases (pre-existing joint conditions) ARE detectable via medical evaluation. Always separate traumatic FM-4a from structural FM-4a in capital assignment.",
        "is_fm_reference": 1,
    },
    {
        "player_name": "Jadeveon Clowney",
        "position": "EDGE",
        "archetype_code": "EDGE-1",
        "mechanism": "South Carolina EDGE with the highest physical ceiling in the 2014 draft class — length, explosion, and run-defense dominance that confirmed EDGE-1 Every-Down Disruptor archetype. The mechanism was confirmed in college across multiple dimensions: pass rush burst, run-defense gap control, and pursuit from backside. FM-4 activated through a cumulative soft-tissue pattern that prevented the technique sequencing required to build on the physical ceiling.",
        "translation_outcome": "PARTIAL",
        "fm_code": "FM-4",
        "fm_mechanism": "Body Breakdown FM-4b — soft tissue cumulative. Knee and soft-tissue injuries beginning Year 1 prevented the hand-technique development that EDGE-1 requires post-draft. Physical mechanism was real and elite; availability compressed the development window that would have allowed technique to complement athleticism. FM-1 co-activated as a result — the technique that was supposed to develop behind the athleticism never arrived because the body could not sustain the development reps.",
        "outcome_summary": "EDGE-1 FM-4b partial: highest physical ceiling in class, soft-tissue pattern began Year 1 and prevented technique sequencing; career peak of 10 sacks in a season despite elite athletic mechanism; the primary FM-4b reference case for EDGE and the Clowney Warning embedded in the EDGE evaluation framework.",
        "era_bracket": "2014-2022",
        "peak_years": "2018-2019",
        "comp_confidence": "A",
        "scheme_context": "Houston Texans (Bill O'Brien — limited deployment), Seattle Seahawks (Pete Carroll — peak production), Tennessee Titans, Cleveland Browns. Production in healthier seasons confirmed mechanism. Availability, not mechanism, was the limiting variable.",
        "signature_trait": "The 2014 fumble recovery against Michigan — strip sack in a single play that showed every EDGE-1 attribute simultaneously — followed by the career arc showing that the mechanism confirmation was real and the body was the variable that prevented the All-Pro ceiling from being reached consistently.",
        "pre_draft_signal": "FM-4 PARTIALLY DETECTABLE: South Carolina medical evaluation in 2014 showed microfracture surgery history (2012) and soft-tissue workload concerns from the 2013 season. The pre-draft signal was present in the medical report. Capital was priced on physical ceiling without explicit FM-4 capital discount for the documented soft-tissue history. DraftOS principle: documented soft-tissue history at EDGE = FM-4b flag + minimum one-tier confidence reduction regardless of physical ceiling.",
        "is_fm_reference": 1,
    },
    {
        "player_name": "Marcus Lattimore",
        "position": "RB",
        "archetype_code": "RB-1",
        "mechanism": "South Carolina RB with confirmed RB-1 Early-Down Hammer mechanism and the highest college production rate of his era — before two catastrophic knee injuries (ACL in 2011, catastrophic multi-ligament in 2012) removed the mechanism entirely before the NFL career began. The FM-4 lesson: mechanism confirmation in college does not transfer when the physical mechanism has been structurally compromised before the professional career begins.",
        "translation_outcome": "MISS",
        "fm_code": "FM-4",
        "fm_mechanism": "Body Breakdown FM-4a — structural/orthopedic, pre-draft. Two ACL-level injuries before the draft eliminated the explosion and lateral agility that defined the confirmed RB-1 mechanism. The body could not be rebuilt to the pre-injury mechanism specification. San Francisco drafted the mechanism confirmation, not the current physical capability.",
        "outcome_summary": "RB-1 FM-4a pre-draft structural bust: mechanism confirmed before injuries, mechanism not recoverable to draft-value threshold after injuries; never played an NFL game at starter level; the definitive pre-draft FM-4a structural case and primary warning for evaluating RBs with documented multi-ligament history.",
        "era_bracket": "2013 (drafted)",
        "peak_years": "None at NFL level",
        "comp_confidence": "A",
        "scheme_context": "San Francisco 49ers (Jim Harbaugh). Medical evaluation at draft time showed mechanism limitation. Capital invested in pre-injury production record.",
        "signature_trait": "The 2010 South Carolina film — before the first ACL injury — that showed a complete RB-1 mechanism operating at All-Pro physical output, followed by the 2013 combine medical evaluation showing bilateral knee structure that could not reproduce the pre-injury explosion.",
        "pre_draft_signal": "CLEARLY VISIBLE AND DOCUMENTED: Two major knee injuries before the draft, including a catastrophic multi-ligament injury in 2012 that required 18+ months of recovery. The pre-draft signal was not missed — it was documented in every evaluation. Capital decision was made on the pre-injury mechanism record rather than the post-injury physical capability. DraftOS principle: FM-4a structural with documented multi-ligament pre-draft history = maximum Tier C evaluation confidence regardless of pre-injury production.",
        "is_fm_reference": 1,
    },
    {
        "player_name": "Robert Griffin III",
        "position": "QB",
        "archetype_code": "QB-3",
        "mechanism": "Baylor QB with confirmed QB-3 Dual-Threat Weapon mechanism — speed, decision-making in read-option, and accuracy on designed rollouts. The mechanism was real and productive. FM-4 activated through a structural knee injury in Year 1 that the organization did not protect adequately, removing the speed component of the mechanism permanently.",
        "translation_outcome": "MISS",
        "fm_code": "FM-4",
        "fm_mechanism": "Body Breakdown FM-4a — structural/orthopedic. Knee ligament injury in 2012 NFC Wildcard game, returned too early under organizational pressure, compounding the structural damage. Speed component of QB-3 mechanism permanently reduced below NFL starter threshold. Without the speed component, QB-3 becomes QB-2 with inadequate processing — a non-starter profile.",
        "outcome_summary": "QB-3 FM-4a bust: mechanism confirmed and functional in Year 1; organizational decision to return from injury before structural recovery reduced the speed component permanently; career collapsed after 2012 season; the primary organizational-FM-4 compound case and the warning against organizational mismanagement of the FM-4 recovery window.",
        "era_bracket": "2012-2020",
        "peak_years": "2012 (ROY season)",
        "comp_confidence": "A",
        "scheme_context": "Washington (Mike Shanahan — mechanism confirmed in 2012, then organizational mismanagement of injury), Cleveland Browns, Baltimore Ravens. No organization after Washington was able to reproduce the mechanism because the physical component had been permanently reduced.",
        "signature_trait": "The 2012 playoff game against Seattle — RG3 playing on a functionally compromised knee under organizational pressure — that produced the irreversible structural damage and ended the confirmed QB-3 mechanism permanently within a single game.",
        "pre_draft_signal": "FM-4 PRE-DRAFT NOT DETECTABLE: No structural indicator at Baylor. ACL history (2009) was documented but considered fully recovered. The FM-4 activation was organizational, not structural — the injury itself was manageable but the organizational response created the permanent damage. DraftOS implication: FM-4 risk for speed-mechanism QBs (QB-3) should include organizational FM-4 protection commitment as part of capital decision — not just player structural assessment.",
        "is_fm_reference": 1,
    },

    # ── FM-5: MOTIVATION CLIFF (6 of 9 records — highest confidence) ───────
    {
        "player_name": "Randy Moss",
        "position": "WR",
        "archetype_code": "WR-2",
        "mechanism": "Marshall WR with the highest confirmed ceiling in the WR-2 Speed Creator archetype — vertical separation rate, contested catch mechanism, and deep-ball production that defined the position for a decade. FM-5 post-contract: the physical tools were real and sustained; the motivation to develop the full route tree and maintain peak conditioning fluctuated with contract security.",
        "translation_outcome": "PARTIAL",
        "fm_code": "FM-5",
        "fm_mechanism": "Motivation Cliff — post-contract, WR-specific. Moss's physical mechanism was confirmed elite and sustained through proper motivation cycles. FM-5 activated cyclically: peak production during contract years (Vikings 1998-2004, Patriots 2007) and below-threshold production during security periods (Oakland 2005-2006). The WR-2 FM-5 pattern: security removes the drive to sustain the physical tools and route tree development that the archetype requires.",
        "outcome_summary": "WR-2 FM-5 post-contract partial: highest WR-2 ceiling in the database, motivation cliff cyclically compressed production; career below All-Pro consistency but above average starter threshold across motivated seasons; the primary WR FM-5 post-contract reference case.",
        "era_bracket": "1998-2010",
        "peak_years": "1998-2003, 2007",
        "comp_confidence": "A",
        "scheme_context": "Minnesota Vikings (Denny Green — peak production), Oakland Raiders (Norv Turner — FM-5 active, minimum effort documented), New England Patriots (Belichick — FM-5 suppressed through accountability structure), San Francisco 49ers. Production correlated with motivational context, not scheme.",
        "signature_trait": "The 2007 New England season — 23 touchdowns with Brady, record-breaking production — that represented FM-5 suppression through organizational accountability and a contract motivation year, followed by the documented Oakland seasons where effort was publicly acknowledged as below threshold.",
        "pre_draft_signal": "FM-5 INDICATORS PRESENT AND DOCUMENTED: Marshall 1997 — inconsistent effort in non-conference games documented in scouting reports. C2 (motivation) concerns noted by multiple teams. Draft position suppressed (Round 1 Pick 21) by character concerns that were FM-5 indicators. The Schwesinger Rule inverse: when C2 is documented inconsistent pre-draft, FM-5 should be rated as structural, not conditional. Moss's career confirms the C2 inconsistency pattern predicted the FM-5 activation cycle.",
        "is_fm_reference": 1,
    },
    {
        "player_name": "Ryan Leaf",
        "position": "QB",
        "archetype_code": "QB-2",
        "mechanism": "Washington State QB with confirmed physical ceiling — arm talent, size, and production in a system that required real processing. The mechanism was partially confirmed: Leaf showed full-field read capability in the Rose Bowl under pressure. FM-3 co-activation was suspected but not confirmed. FM-5 was the primary mechanism: motivation and psychological profile (C2 and C3) were below threshold pre-draft across multiple independent evaluations.",
        "translation_outcome": "MISS",
        "fm_code": "FM-5",
        "fm_mechanism": "Motivation Cliff — pre-contract, substance-variant. FM-5 activated before NFL career began at the level required to sustain the development and preparation that QB-2 requires. C2 and C3 below threshold — the Smith Rule triggered pre-draft. The compound FM-3/FM-5 at QB-2 produced the fastest organizational collapse in the quarterback database.",
        "outcome_summary": "QB-2 FM-5 and FM-3 compound bust: pre-contract motivation cliff with substance-variant activation; C2 and C3 below threshold confirmed pre-draft; organizational dysfunction compounded; Round 1 Pick 2 capital returned 4 career wins — the primary QB FM-5 pre-contract case and the Smith Rule calibration anchor.",
        "era_bracket": "1998-2001",
        "peak_years": "None at NFL starter level",
        "comp_confidence": "A",
        "scheme_context": "San Diego Chargers (June Jones, Mike Riley). No coordinator was able to establish a preparation structure within the FM-5 profile. The motivation cliff was pre-contract — the draft capital itself was the peak.",
        "signature_trait": "The 1998 Rose Bowl performance — the one game that confirmed a processing mechanism was potentially present — followed by the immediate post-draft behavior that confirmed the C2 and C3 profile was below threshold and that the Rose Bowl was the ceiling, not the floor.",
        "pre_draft_signal": "FM-5 CONFIRMED PRE-DRAFT: C2 (motivation) and C3 (psychological profile) concerns were documented by the Indianapolis Colts evaluation, the San Diego Chargers evaluation, and multiple independent scouts. Smith Rule triggered: C1 indicators present (behavioral incidents in college) + C2 below threshold. The pre-draft signal was not missed — it was present, documented, and then overridden by physical ceiling projection. Ryan Leaf is the primary Smith Rule calibration case: when C2 is below threshold at QB, FM-5 is structural, not conditional.",
        "is_fm_reference": 1,
    },
    {
        "player_name": "Aldon Smith",
        "position": "EDGE",
        "archetype_code": "EDGE-2",
        "mechanism": "Missouri EDGE with confirmed EDGE-2 Speed Rusher mechanism — first-step burst and hand sequence that produced 33.5 sacks in his first three NFL seasons, the highest production rate in EDGE history over that span. FM-5 activated through the substance-variant pattern: C1 (criminal history) and C2 (motivation) below threshold, Smith Rule triggered post-confirmation.",
        "translation_outcome": "MISS",
        "fm_code": "FM-5",
        "fm_mechanism": "Motivation Cliff — substance-variant, post-confirmation. The physical mechanism was confirmed and elite. FM-5 activated through a substance abuse pattern that produced multiple legal incidents and suspensions, removing the EDGE-2 mechanism from the field at the peak of its production window. Smith Rule retrospective: C1 indicators were present pre-draft and discounted against physical ceiling.",
        "outcome_summary": "EDGE-2 FM-5 substance-variant bust: highest sack rate in EDGE history over first three seasons, substance-variant FM-5 activated, suspensions and team releases removed the mechanism from production at peak; career essentially ended at age 26; the primary EDGE FM-5 substance case and Smith Rule application reference.",
        "era_bracket": "2011-2020",
        "peak_years": "2011-2013",
        "comp_confidence": "A",
        "scheme_context": "San Francisco 49ers (Jim Harbaugh — mechanism at peak), Oakland Raiders (multiple coordinators — FM-5 active). Production during suspension periods: zero. Physical mechanism confirmed elite during available windows.",
        "signature_trait": "The 2012 San Francisco 49ers season — 19.5 sacks in 16 games, the highest single-season sack total of the decade to that point — that confirmed the EDGE-2 mechanism at elite tier, followed by the first DUI arrest weeks after the season ended that began the FM-5 activation sequence.",
        "pre_draft_signal": "FM-5 INDICATORS PRESENT: Missouri 2010 — behavioral incidents documented pre-draft. C1 indicators present (substance-related concern flagged in background check). Smith Rule threshold: C1 active + C2 below threshold = mandatory FM-5 flag. The pre-draft C2 evaluation produced concern that was discounted against the 2011 production projection. Smith Rule was not applied. Retrospective: Smith Rule application would have produced a one-round capital discount and explicit FM-5 flag that matched the career outcome.",
        "is_fm_reference": 1,
    },
    {
        "player_name": "Josh Gordon",
        "position": "WR",
        "archetype_code": "WR-1",
        "mechanism": "Baylor WR with confirmed WR-1 Route Technician mechanism expression and the physical tools to sustain it — size, speed, and contested-catch ability that produced the highest single-season receiving yards in NFL history (2013). FM-5 activated through the substance-variant pattern before, during, and after the peak production season.",
        "translation_outcome": "MISS",
        "fm_code": "FM-5",
        "fm_mechanism": "Motivation Cliff — substance-variant, persistent. The physical mechanism was confirmed and elite. FM-5 was present pre-draft, active during college, and did not resolve at the NFL level. The substance-variant pattern produced repeated suspensions that removed the mechanism from production across what should have been a six to eight year prime window.",
        "outcome_summary": "WR-1 FM-5 substance-variant bust: highest single-season receiving total in history (2013), substance-variant FM-5 active throughout career; available seasons produced elite production; total NFL career games severely compressed by suspensions; the definitive WR FM-5 substance case.",
        "era_bracket": "2012-2022",
        "peak_years": "2013",
        "comp_confidence": "A",
        "scheme_context": "Cleveland Browns (multiple coordinators), New England Patriots (Belichick — limited), multiple teams on short-term deals. Production in available games consistently above threshold; availability was the only variable.",
        "signature_trait": "The 2013 Cleveland season — 1,646 yards in 14 games (117.6 yards per game average, the highest in NFL history) — that confirmed the WR-1 mechanism at elite tier while Gordon was playing under a substance abuse suspension calendar that should have disqualified the capital investment.",
        "pre_draft_signal": "FM-5 CONFIRMED PRE-DRAFT: Baylor suspension and Wichita State transfer for substance-related reasons were documented at the time of the 2012 Supplemental Draft. C1 indicators confirmed active. C2 concerns documented. Smith Rule triggered. Capital (Round 2 Supplemental Pick) was invested despite confirmed active FM-5 indicators. Retrospective: the 2013 production season confirms the mechanism was real; the Smith Rule application confirms the career outcome was predictable from the pre-draft profile.",
        "is_fm_reference": 1,
    },
    {
        "player_name": "Travis Henry",
        "position": "RB",
        "archetype_code": "RB-2",
        "mechanism": "Tennessee RB with confirmed RB-2 Inside Zone Specialist mechanism — contact balance and vision in the zone run game that produced starter-level NFL production when available. FM-5 substance-variant activated through the Smith Rule pattern: C1 active, C2 below threshold, career compressed by suspensions.",
        "translation_outcome": "MISS",
        "fm_code": "FM-5",
        "fm_mechanism": "Motivation Cliff — substance-variant. Mechanism was confirmed and functional. FM-5 compressed the production window through repeated suspensions. The Smith Rule retrospective: C1 indicators were present pre-draft and not applied to capital.",
        "outcome_summary": "RB-2 FM-5 substance-variant: mechanism confirmed and functional in available seasons; career suspended three times for substance violations; production window compressed from projected 8-10 years to fewer than 5 functional seasons; confirms Smith Rule is position-universal.",
        "era_bracket": "2001-2008",
        "peak_years": "2002-2006",
        "comp_confidence": "A",
        "scheme_context": "Buffalo Bills, Tennessee Titans, Denver Broncos. Productive in available seasons within zone-run systems. Availability was the career variable.",
        "signature_trait": "The 2006 Denver season — 1,211 yards in a zone-run system that confirmed RB-2 mechanism at starter threshold — followed by the 2008 one-year suspension that ended the career at age 30, while the physical mechanism was still above threshold.",
        "pre_draft_signal": "FM-5 INDICATORS PRESENT: Tennessee 2001 — substance-related behavior documented in pre-draft background. C1 indicators present. Smith Rule applicable: C1 active + C2 concern = mandatory FM-5 flag. Capital was invested without explicit FM-5 flag or capital discount. The Smith Rule is position-universal — RB FM-5 discount applies identically to premium position FM-5 discount.",
        "is_fm_reference": 1,
    },
    {
        "player_name": "Von Miller",
        "position": "EDGE",
        "archetype_code": "EDGE-1",
        "mechanism": "Texas A&M EDGE with confirmed EDGE-1 Every-Down Disruptor mechanism — hand technique, counter package, and first-step burst combination that produced the highest sustained sack rate of his generation. FM-5 indicators were present pre-draft (C2 concerns, substance program at Texas A&M) but C2 was above the Smith Rule threshold. FM-5 activated briefly (2013 suspension) but did not compress the career window, confirming the C2 threshold distinction.",
        "translation_outcome": "HIT",
        "fm_code": "FM-5",
        "fm_mechanism": "N/A — FM-5 indicators present but did not activate to career-compressing level. C2 above Smith Rule threshold. 2013 suspension (substance) was isolated, not compound. RESOLUTION CASE: FM-5 risk present pre-draft through C1 indicator and C2 concern; resolved because C2 above threshold prevented career-level compression. Contrast with Aldon Smith (same era, same position, lower C2 score) — different career outcome.",
        "outcome_summary": "EDGE-1 FM-5 risk resolved: substance indicator pre-draft, C2 above Smith Rule threshold, single isolated suspension in Year 3, Hall of Fame career arc — the FM-5 resolution reference case and the C2 threshold calibration anchor that distinguishes isolated incidents from structural motivation cliff.",
        "era_bracket": "2011-present",
        "peak_years": "2012-2016, 2021",
        "comp_confidence": "A",
        "scheme_context": "Denver Broncos (John Fox, Gary Kubiak, Vic Fangio — sustained production), Los Angeles Rams (Sean McVay — Super Bowl peak). Production sustained across scheme families, confirming system-transcendent mechanism.",
        "signature_trait": "The 2015 Super Bowl 50 performance — 2.5 sacks, MVP — that occurred despite the 2013 suspension history, confirming that the C2 threshold above the Smith Rule floor allowed the physical mechanism to sustain through the isolated incident.",
        "pre_draft_signal": "FM-5 INDICATORS PRESENT, C2 ABOVE THRESHOLD: Texas A&M substance program participation documented pre-draft. C1 indicator: present. C2 evaluation: above Smith Rule threshold (motivation concerns present but not pervasive across multiple independent evaluations). Smith Rule distinction: the threshold is C2 BELOW threshold, not C2 concerns present. Von Miller vs. Aldon Smith: same C1 indicator, different C2 score, different career outcome — the calibration case for the Smith Rule C2 threshold.",
        "is_fm_reference": 1,
    },

    # ── FM-6: ROLE MISMATCH (7 records) ────────────────────────────────────
    {
        "player_name": "Greg Robinson",
        "position": "OT",
        "archetype_code": "OT-1",
        "mechanism": "Auburn OT with confirmed athleticism and movement profile — lateral quickness and physical tools that projected as an elite blindside protector. FM-6 activated through scheme mismatch: Robinson was drafted as a pass-protection-first OT and deployed in a zone-blocking system that required the lateral footwork and hand-sequence combination he possessed, but then moved to teams running gap and power schemes that required anchor strength he never confirmed.",
        "translation_outcome": "MISS",
        "fm_code": "FM-6",
        "fm_mechanism": "Role Mismatch FM-6a — scheme mismatch. The athleticism mechanism was real. The scheme requirement at each NFL stop did not align with the confirmed mechanism. Zone-blocking system deployment would have activated the mechanism; gap/power deployment did not. The player didn't fail. The evaluation failed to match mechanism to deployment context.",
        "outcome_summary": "OT-1 FM-6a scheme mismatch bust: athletic mechanism confirmed, scheme alignment between confirmed mechanism and deployment context never achieved; Round 1 Pick 2 capital returned below-starter production across five teams; the primary OL FM-6 scheme mismatch case.",
        "era_bracket": "2014-2022",
        "peak_years": "None at NFL starter level",
        "comp_confidence": "A",
        "scheme_context": "St. Louis Rams (zone-blocking — closest fit, still below threshold), Jacksonville Jaguars (multiple schemes), Detroit Lions, Cleveland Browns. Never deployed in a confirmed zone-first system with the coaching infrastructure to develop the technical elements his mechanism required.",
        "signature_trait": "The 2014 Auburn tape showing lateral movement and athletic displacement that read as OT-1 mechanism — followed by the NFL career where the scheme requirement at every stop required anchor strength and gap-blocking technique that were below threshold, while the zone-blocking mechanism was never given adequate deployment context.",
        "pre_draft_signal": "FM-6 DETECTABLE PRE-DRAFT: Auburn's zone-blocking system amplified Robinson's athletic mechanism. Scheme Versatility — specifically zone vs. gap technique — was not confirmed in college. Pre-draft evaluation noted the zone-blocking fit without explicitly flagging the gap-scheme risk. Scheme Family Note required for all OL archetypes: had this been applied, the FM-6 flag would have been explicit and a scheme-alignment requirement would have been part of the capital decision.",
        "is_fm_reference": 1,
    },
    {
        "player_name": "Cordarrelle Patterson",
        "position": "WR",
        "archetype_code": "WR-5",
        "mechanism": "Tennessee WR with a confirmed return/gadget specialist mechanism and YAC ability in space. FM-6 activated through role mismatch: drafted as a WR-3 YAC Creator and deployed as an outside receiver in a traditional passing offense rather than as a gadget/multipurpose back whose mechanism required manufactured touches and designed space creation.",
        "translation_outcome": "PARTIAL",
        "fm_code": "FM-6",
        "fm_mechanism": "Role Mismatch FM-6b — role mismatch within correct position. The mechanism was confirmed in a specific deployment context (gadget/multipurpose with manufactured touches) and not transferable to the traditional WR deployment context that multiple teams assigned. When eventually deployed correctly (Atlanta Falcons, 2021-2022), the mechanism produced at expected levels — confirming the player mechanism was real and the deployment was the failure variable.",
        "outcome_summary": "WR-5/RB FM-6b partial: gadget mechanism real, traditional WR deployment repeated across five teams confirmed the mismatch; eventual correct deployment as multipurpose back produced Pro Bowl level output at age 30; the definitive FM-6b role-within-position mismatch case.",
        "era_bracket": "2013-present",
        "peak_years": "2021-2022 (correct deployment)",
        "comp_confidence": "A",
        "scheme_context": "Minnesota Vikings (traditional WR deployment — mismatch), Oakland Raiders, New England Patriots, Chicago Bears (partial fit), Cleveland Browns, Atlanta Falcons (Arthur Smith — correct deployment, Pro Bowl). Production correlated directly with deployment accuracy.",
        "signature_trait": "The 2021 Atlanta season — 618 rushing yards, 548 receiving yards, 11 touchdowns as a multipurpose back — that confirmed the mechanism at Pro Bowl level eight years after the draft, once the deployment context finally matched the confirmed mechanism.",
        "pre_draft_signal": "FM-6 DETECTABLE PRE-DRAFT: Tennessee 2012 tape showed a player whose mechanism operated in manufactured-touch environments — wide receiver screens, gadget formations, kick returns. The mechanism was player-generated but context-dependent. Landing Spot Note required for WR-3 WR-4 archetypes: had this been applied, the WR-5 gadget classification would have prevented traditional WR deployment expectations across five NFL teams.",
        "is_fm_reference": 1,
    },
    {
        "player_name": "Justin Blackmon",
        "position": "WR",
        "archetype_code": "WR-1",
        "mechanism": "Oklahoma State WR with confirmed WR-1 Route Technician mechanism — the highest WR-1 college production grade of his draft class. FM-6 did not activate as role mismatch — FM-5 was the primary bust mode (substance). Included in FM-6 file because the organizational deployment compounded the FM-5 activation: Jacksonville deployed Blackmon in a role that required every-down production without the supporting cast that WR-1 requires, accelerating the FM-5 activation under organizational stress.",
        "translation_outcome": "MISS",
        "fm_code": "FM-6",
        "fm_mechanism": "Role Mismatch FM-6d — organizational infrastructure mismatch. WR-1 mechanism confirmed. Organizational context (rebuilding franchise, inadequate QB, below-threshold supporting cast) placed a system-dependent archetype in a role requiring immediate production without the infrastructure that WR-1 requires. FM-5 compound with substance-variant: the organizational infrastructure mismatch accelerated the FM-5 activation sequence.",
        "outcome_summary": "WR-1 FM-6d and FM-5 compound: mechanism confirmed at highest college grade in class; organizational infrastructure mismatch placed system-dependent archetype without required QB and supporting cast; FM-5 substance-variant activated under organizational stress; Round 1 Pick 5 capital returned 19 career games.",
        "era_bracket": "2012-2015",
        "peak_years": "2012 (19 games across two seasons)",
        "comp_confidence": "A",
        "scheme_context": "Jacksonville Jaguars (Mike Mularkey, Gus Bradley). Rebuilding franchise with below-threshold QB infrastructure across Blackmon's entire available career. WR-1 mechanism requires competent QB and designed route-tree deployment — neither was present.",
        "signature_trait": "The Oklahoma State 2011 tape — the highest college WR-1 production grade of the 2012 class, confirming the route precision mechanism — followed by the Jacksonville reality of a WR-1 operating without the QB infrastructure that the archetype requires, in a rebuilding environment where the organizational FM-6d stress accelerated the FM-5 activation.",
        "pre_draft_signal": "FM-5 INDICATORS PRESENT: Substance concerns documented at Oklahoma State. Smith Rule applicable. FM-6d DETECTABLE: Jacksonville's organizational profile at draft time — rebuilding, below-threshold QB, inadequate infrastructure — was known. Landing Spot Note for WR-1 archetypes should have flagged: QB Dependency and system infrastructure audit required. Both signals were present and not applied to capital.",
        "is_fm_reference": 1,
    },
    {
        "player_name": "Darrius Heyward-Bey",
        "position": "WR",
        "archetype_code": "WR-2",
        "mechanism": "Maryland WR with confirmed 4.30 speed but unconfirmed WR-2 separation mechanism — route tree development was below NFL starter threshold at draft. FM-6c activated: a developmental archetype was placed in a role requiring immediate production as a WR1 in Oakland's offense, accelerating the exposure of the mechanism gap before development could occur.",
        "translation_outcome": "MISS",
        "fm_code": "FM-6",
        "fm_mechanism": "Role Mismatch FM-6c — timeline mismatch. Developmental WR archetype placed in a role requiring immediate production. The speed mechanism was real. The route development required to convert speed into WR-2 separation was not complete at draft and required a 2-3 year development window. Oakland deployed DHB as an immediate production asset, eliminating the development window before the mechanism could develop.",
        "outcome_summary": "WR-2 FM-6c timeline mismatch bust: speed mechanism confirmed, route development below NFL starter threshold at draft, immediate production deployment eliminated the development window, career below starter threshold across seven seasons; confirms developmental archetypes require explicit deployment timeline commitment from drafting organization.",
        "era_bracket": "2009-2016",
        "peak_years": "2011 (functional, Oakland)",
        "comp_confidence": "A",
        "scheme_context": "Oakland Raiders (Tom Cable — immediate production expectation), Indianapolis Colts (Chuck Pagano — developmental deployment, too late). Production in Indianapolis showed mechanism development was occurring — confirming timeline mismatch was the variable, not mechanism absence.",
        "signature_trait": "The Oakland 2009 deployment — Round 1 Pick 7 receiving WR1 expectation — that confirmed the timeline mismatch before the first regular season game. DHB needed 2-3 years of route development reps in a patient deployment; he received immediate production expectation instead.",
        "pre_draft_signal": "FM-6 DETECTABLE PRE-DRAFT: Maryland 2008 route tree was below NFL starter threshold — visible on tape. The 4.30 speed dominated the evaluation. The Development Timeline Rule — developmental archetype placed in an immediate-production role — requires an explicit deployment timeline commitment from the drafting organization. Oakland's immediate production expectation at Round 1 Pick 7 was public pre-draft. Capital was assigned without confirming the organizational timeline matched the developmental archetype requirement.",
        "is_fm_reference": 1,
    },
    {
        "player_name": "Kevin White",
        "position": "WR",
        "archetype_code": "WR-2",
        "mechanism": "West Virginia WR with confirmed athleticism profile (4.35 speed, elite RAS) but scheme-amplified college production in a spread offense that manufactured separation before the snap. FM-6c plus FM-4: developmental timeline mismatch compounded by FM-4 that eliminated the development window entirely. Multiple serious injuries (fibula, stress fracture) across Years 1-3 before mechanism could develop.",
        "translation_outcome": "MISS",
        "fm_code": "FM-6",
        "fm_mechanism": "Role Mismatch FM-6c with FM-4 compound: developmental WR archetype placed in immediate production role (Chicago Year 1 WR1 expectation), then FM-4 eliminated the development window. The compound FM-6c/FM-4 is the most expensive pattern in the WR database — developmental timeline mismatch + body breakdown before development occurs produces zero career production despite legitimate athletic mechanism.",
        "outcome_summary": "WR-2 FM-6c and FM-4 compound bust: athletic mechanism confirmed, spread system amplified college production above mechanism grade, Round 1 Pick 7 capital assigned developmental archetype to immediate-production role, FM-4 eliminated development window in Years 1-3; 25 career catches — the definitive FM-6c/FM-4 compound case.",
        "era_bracket": "2015-2021",
        "peak_years": "None at NFL starter level",
        "comp_confidence": "A",
        "scheme_context": "Chicago Bears (John Fox, Matt Nagy). Multiple coordinators, all with immediate WR1 production expectation at Round 1 Pick 7 capital. FM-4 interrupted every attempted development cycle.",
        "signature_trait": "The 2015 pre-draft West Virginia tape — elite athletic profile in a spread offense showing manufactured separation — that drove the Round 1 Pick 7 investment, followed by the fibula injury in Year 1 training camp that began the FM-4 pattern before the mechanism could be developed.",
        "pre_draft_signal": "FM-6 DETECTABLE: West Virginia spread system generated scheme-amplified production. PAA Q2 competition discount should have produced a developmental archetype classification, not a Day 1 starter expectation. FM-4 NOT DETECTABLE PRE-DRAFT (no structural indicator). The FM-6c mismatch was fully detectable: Round 1 Pick 7 capital requires immediate production; a developmental archetype classification requires a development timeline that Round 1 Pick 7 expectations cannot accommodate.",
        "is_fm_reference": 1,
    },
    {
        "player_name": "Trent Richardson",
        "position": "RB",
        "archetype_code": "RB-1",
        "mechanism": "Alabama RB with confirmed RB-1 Early-Down Hammer mechanism — power, vision, and inside running production that was elite against SEC competition in a system designed to manufacture clean run lanes. FM-6 activated through role mismatch: deployed as a three-down every-down back in a Cleveland offense that required the receiver-back function he had not confirmed, while the confirmed interior running mechanism was deployed in a situation where the offensive line could not execute the blocking scheme.",
        "translation_outcome": "MISS",
        "fm_code": "FM-6",
        "fm_mechanism": "Role Mismatch FM-6a and FM-6d compound: scheme mismatch (Cleveland's offensive line could not execute the gap/power blocking the RB-1 mechanism required) plus organizational infrastructure mismatch (rebuilding franchise without the OL infrastructure that RB-1 requires). FM-6 is organizational, not player-generated — Richardson's mechanism was real; the organizational context that would have activated it was never present.",
        "outcome_summary": "RB-1 FM-6 compound bust: mechanism confirmed in Alabama system with confirmed gap/power OL infrastructure; Cleveland deployment without OL infrastructure for RB-1 mechanism; trade to Indianapolis confirmed FM-6 — different organization, same below-threshold production; Round 1 Pick 3 capital returned 3.0 YPC across career — mechanism never given the infrastructure it required.",
        "era_bracket": "2012-2019",
        "peak_years": "None at NFL starter level",
        "comp_confidence": "A",
        "scheme_context": "Cleveland Browns (Pat Shurmur, Rob Chudzinski — below-threshold OL infrastructure), Indianapolis Colts (Chuck Pagano — below-threshold RB deployment). Neither team provided the gap/power OL execution the confirmed RB-1 mechanism requires.",
        "signature_trait": "The Alabama 2011 film — dominated runs against SEC front sevens in a gap/power scheme with a dominant OL — that confirmed the RB-1 mechanism in the ideal deployment context, followed by the Cleveland tape where the same player behind a below-threshold OL produced 3.0 YPC against the same NFL competition tier.",
        "pre_draft_signal": "FM-6 PARTIALLY DETECTABLE: Cleveland's organizational profile at draft time — rebuilding OL, unclear scheme commitment — was publicly documented. RB-1 mechanism requires a dominant OL infrastructure; Cleveland's OL grade was below threshold at draft. Scheme Family Note for OL and implied RB deployment context should have been applied: if the OL cannot execute gap/power blocking, Round 1 Pick 3 investment in an RB-1 mechanism is FM-6 risk confirmed at the time of capital assignment.",
        "is_fm_reference": 1,
    },
    {
        "player_name": "Chris Borland",
        "position": "ILB",
        "archetype_code": "ILB-1",
        "mechanism": "Wisconsin ILB with confirmed ILB-1 Sideline-to-Sideline mechanism — processing, pursuit, and tackling production that produced a Pro Bowl-caliber rookie season. FM-6 did not activate as role mismatch. Included as the FM-6 resolution case: Borland retired voluntarily due to concussion concerns — the only FM-6 database case where the player's self-assessment of FM-4 risk (structural, cumulative) produced the outcome before organizational misdeployment could. Not a bust. A resolution case.",
        "translation_outcome": "PARTIAL",
        "fm_code": "FM-6",
        "fm_mechanism": "N/A — FM-6 did not activate. Player-initiated retirement removed the mechanism from deployment before organizational mismatch or FM-4 could activate. RESOLUTION CASE: The only database case where the player's own FM-4 risk assessment produced the correct capital outcome for the player (career preservation) at the cost of the organization's capital return. The FM-6 prevention protocol worked in reverse — the player prevented his own FM-4.",
        "outcome_summary": "ILB-1 voluntary retirement resolution case: mechanism confirmed at Pro Bowl level in single season; player self-assessed FM-4 cumulative brain trauma risk; voluntary retirement Year 2; the FM-6 prevention reference case — not an FM-6 bust, but included because the deployment timeline that FM-6 prevention requires applies equally to player self-assessment of availability.",
        "era_bracket": "2014-2015",
        "peak_years": "2014 (Pro Bowl-caliber single season)",
        "comp_confidence": "A",
        "scheme_context": "San Francisco 49ers (Jim Tomsula). Single season deployment before voluntary retirement. Mechanism confirmed in available season.",
        "signature_trait": "The 2014 San Francisco season — 108 tackles, 2 sacks in 14 games as a rookie — that confirmed ILB-1 mechanism at Pro Bowl level, followed by the voluntary retirement announcement that produced the correct outcome for the player and a capital loss for the organization.",
        "pre_draft_signal": "FM-6 NOT APPLICABLE: Voluntary retirement is not an FM-6 case in the traditional sense. The DraftOS implication: FM-4 cumulative brain trauma risk is the one FM-4 variant that can produce voluntary retirement independent of organizational deployment. ILB and S archetypes with documented head impact history pre-draft carry this as a specific FM-4d sub-risk that is distinct from structural/orthopedic FM-4a.",
        "is_fm_reference": 1,
    },
]

# ---------------------------------------------------------------------------
# MIGRATION & DB UTILITIES
# ---------------------------------------------------------------------------

def backup_db() -> Path:
    BACKUP_DIR.mkdir(parents=True, exist_ok=True)
    ts = datetime.datetime.now().strftime("%Y%m%dT%H%M%S")
    dest = BACKUP_DIR / f"draftos_pre0046_{ts}.sqlite"
    shutil.copy2(DB_PATH, dest)
    return dest


def connect():
    conn = sqlite3.connect(DB_PATH)
    conn.row_factory = sqlite3.Row
    conn.execute("PRAGMA foreign_keys = ON")
    return conn


def migration_applied(conn, name: str) -> bool:
    row = conn.execute(
        "SELECT 1 FROM meta_migrations WHERE name = ?", (name,)
    ).fetchone()
    return row is not None


def column_exists(conn, table: str, column: str) -> bool:
    rows = conn.execute(f"PRAGMA table_info({table})").fetchall()
    return any(r["name"] == column for r in rows)


def apply_migration(conn, apply: bool) -> None:
    """Add pre_draft_signal and is_fm_reference columns."""
    needs_signal = not column_exists(conn, "historical_comps", "pre_draft_signal")
    needs_flag   = not column_exists(conn, "historical_comps", "is_fm_reference")

    if apply:
        if needs_signal:
            conn.execute("ALTER TABLE historical_comps ADD COLUMN pre_draft_signal TEXT")
            print("  APPLY: Added column pre_draft_signal TEXT")
        else:
            print("  SKIP: pre_draft_signal already exists")

        if needs_flag:
            conn.execute(
                "ALTER TABLE historical_comps ADD COLUMN is_fm_reference INTEGER NOT NULL DEFAULT 0"
            )
            print("  APPLY: Added column is_fm_reference INTEGER DEFAULT 0")
        else:
            print("  SKIP: is_fm_reference already exists")

        conn.execute(
            "INSERT OR IGNORE INTO meta_migrations (name, applied_at) VALUES (?, datetime('now'))",
            (MIGRATION_NAME,)
        )
        conn.commit()
        print(f"  APPLY: Migration {MIGRATION_NAME} logged")
    else:
        if needs_signal:
            print("  [DRY RUN] Would ALTER TABLE historical_comps ADD COLUMN pre_draft_signal TEXT")
        if needs_flag:
            print("  [DRY RUN] Would ALTER TABLE historical_comps ADD COLUMN is_fm_reference INTEGER DEFAULT 0")
        print(f"  [DRY RUN] Would log migration {MIGRATION_NAME}")


def seed_records(conn, apply: bool) -> None:
    """Insert FM reference records. Idempotent via INSERT OR IGNORE on (player_name, archetype_code).
    If a position comp row already exists for (player_name, archetype_code), updates only the
    is_fm_reference and pre_draft_signal fields — preserving existing position comp content.
    """
    inserted = 0
    updated  = 0
    skipped  = 0

    # Group for dry-run summary
    by_fm: dict[str, list] = {}
    for rec in FM_RECORDS:
        by_fm.setdefault(rec["fm_code"], []).append(rec)

    if not apply:
        print(f"  [DRY RUN] Would insert {len(FM_RECORDS)} FM reference records:")
        for fm, recs in sorted(by_fm.items()):
            print(f"    {fm}: {len(recs)} records")
        print(f"  [DRY RUN] Existing rows with same (player_name, archetype_code) will be")
        print(f"            updated with is_fm_reference=1 and pre_draft_signal (not replaced).")
        return

    for rec in FM_RECORDS:
        try:
            conn.execute(
                """
                INSERT OR IGNORE INTO historical_comps (
                    player_name, position, archetype_code, mechanism,
                    translation_outcome, fm_code, fm_mechanism, outcome_summary,
                    era_bracket, peak_years, comp_confidence, scheme_context,
                    signature_trait, pre_draft_signal, is_fm_reference,
                    created_at, updated_at
                ) VALUES (
                    :player_name, :position, :archetype_code, :mechanism,
                    :translation_outcome, :fm_code, :fm_mechanism, :outcome_summary,
                    :era_bracket, :peak_years, :comp_confidence, :scheme_context,
                    :signature_trait, :pre_draft_signal, :is_fm_reference,
                    datetime('now'), datetime('now')
                )
                """,
                rec
            )
            if conn.execute("SELECT changes()").fetchone()[0] > 0:
                inserted += 1
            else:
                # Row exists — update only the FM-specific fields if not already an FM reference
                conn.execute(
                    """
                    UPDATE historical_comps
                    SET is_fm_reference = 1,
                        pre_draft_signal = :pre_draft_signal,
                        updated_at = datetime('now')
                    WHERE player_name = :player_name
                      AND archetype_code = :archetype_code
                      AND is_fm_reference = 0
                    """,
                    rec
                )
                if conn.execute("SELECT changes()").fetchone()[0] > 0:
                    updated += 1
                else:
                    skipped += 1
        except Exception as e:
            print(f"  ERROR inserting {rec['player_name']}: {e}")

    conn.commit()
    print(f"  APPLY: {inserted} inserted, {updated} updated (existing rows patched), {skipped} skipped (already FM reference)")


# ---------------------------------------------------------------------------
# MAIN
# ---------------------------------------------------------------------------

def main():
    parser = argparse.ArgumentParser(description="Seed FM reference comps — Migration 0046")
    parser.add_argument("--apply", type=int, choices=[0, 1], required=True,
                        help="0 = dry run, 1 = apply")
    args = parser.parse_args()
    apply = bool(args.apply)

    print(f"\n{'='*60}")
    print(f"  seed_fm_reference_comps.py  |  apply={apply}")
    print(f"  DB: {DB_PATH}")
    print(f"{'='*60}\n")

    if not DB_PATH.exists():
        raise SystemExit(f"FAIL: DB not found at {DB_PATH}")

    if apply:
        backup = backup_db()
        print(f"  OK: backup created: {backup}\n")

    with connect() as conn:
        # Check migration status
        already_applied = migration_applied(conn, MIGRATION_NAME)
        if already_applied:
            print(f"  INFO: Migration {MIGRATION_NAME} already applied — skipping ALTER TABLE")
        else:
            print("  Running Migration 0046...")
            apply_migration(conn, apply)

        print(f"\n  Seeding {len(FM_RECORDS)} FM reference records...")
        seed_records(conn, apply)

        if apply:
            # Final verification
            total = conn.execute("SELECT COUNT(*) FROM historical_comps").fetchone()[0]
            fm_count = conn.execute(
                "SELECT COUNT(*) FROM historical_comps WHERE is_fm_reference = 1"
            ).fetchone()[0]
            signal_count = conn.execute(
                "SELECT COUNT(*) FROM historical_comps WHERE is_fm_reference = 1 AND pre_draft_signal IS NOT NULL"
            ).fetchone()[0]
            print(f"\n  VERIFICATION:")
            print(f"    Total historical_comps rows: {total}")
            print(f"    FM reference rows: {fm_count}")
            print(f"    FM rows with pre_draft_signal: {signal_count}")
            if fm_count != signal_count:
                print(f"  WARNING: {fm_count - signal_count} FM rows missing pre_draft_signal!")
            else:
                print(f"    OK: All FM records have pre_draft_signal populated")

    print(f"\n{'='*60}")
    print(f"  {'DONE' if apply else 'DRY RUN COMPLETE'}")
    print(f"{'='*60}\n")


if __name__ == "__main__":
    main()
